
/// A header comment for generated files.
const defaultHeader = '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: directives_ordering
// ignore_for_file: unnecessary_brace_in_string_interps
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: avoid_print
// ignore_for_file: prefer_single_quotes
// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_final_locals
// ignore_for_file: unnecessary_new
// ignore_for_file: unnecessary_string_interpolations
// ignore_for_file: avoid_unnecessary_containers
// ignore_for_file: public_member_api_docs
// --------------------------------------------------
// This file was generated by the `dimengen` package.
// Any changes to this file may be lost during rebuild.
// 
// Generator: https://pub.dev/packages/dimengen
// Author: http://github.com/warioddly
// --------------------------------------------------\n
''';