
/// A header comment for generated files.
const defaultHeader = '''
// --------------------------------------------------
// This file was generated by the `dimengen` package.
// Any changes to this file may be lost during rebuild.
// 
// Generator: https://pub.dev/packages/dimengen
// Author: http://github.com/warioddly
// --------------------------------------------------\n
''';