targets:
  $default:
    builders:
      dimengen:
        generate_for:
          include:
            - lib/**.dart

builders:
  dimengen:
    import: "package:dimengen/builder.dart"
    builder_factories: ["dimengenBuilder"]
    build_extensions: {".dart": ["dimengen.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
