// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'borders.dart';

// **************************************************************************
// BordersGenerator
// **************************************************************************

//
// GENERATED FILE — DO NOT MODIFY BY HAND
// --------------------------------------------------
// This file was generated by the `dimengen` package.
// Any changes to this file may be lost during rebuild.
//
// Generator: https://pub.dev/packages/dimengen
// Author: http://github.com/warioddly
// --------------------------------------------------
//

abstract class Borders {
  const Borders._();

  static const BorderRadius s = BorderRadius.all(Radius.circular(24.0));
  static const BorderRadius sTop = BorderRadius.only(
    topLeft: Radius.circular(24.0),
    topRight: Radius.circular(24.0),
  );
  static const BorderRadius sBottom = BorderRadius.only(
    bottomLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius sLeft = BorderRadius.only(
    topLeft: Radius.circular(24.0),
    bottomLeft: Radius.circular(24.0),
  );
  static const BorderRadius sRight = BorderRadius.only(
    topRight: Radius.circular(24.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius sVertical = BorderRadius.vertical(
    top: Radius.circular(24.0),
    bottom: Radius.circular(24.0),
  );
  static const BorderRadius sHorizontal = BorderRadius.horizontal(
    left: Radius.circular(24.0),
    right: Radius.circular(24.0),
  );
  static const BorderRadius sTopLeft = BorderRadius.only(
    topLeft: Radius.circular(24.0),
  );
  static const BorderRadius sTopRight = BorderRadius.only(
    topRight: Radius.circular(24.0),
  );
  static const BorderRadius sBottomLeft = BorderRadius.only(
    bottomLeft: Radius.circular(24.0),
  );
  static const BorderRadius sBottomRight = BorderRadius.only(
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius sTopLeftBottomRight = BorderRadius.only(
    topLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius sTopRightBottomLeft = BorderRadius.only(
    topRight: Radius.circular(24.0),
    bottomLeft: Radius.circular(24.0),
  );
}
