// dart format width=80
//
// GENERATED FILE — DO NOT MODIFY BY HAND
// --------------------------------------------------
// This file was generated by the `dimengen` package.
// Any changes to this file may be lost during rebuild.
//
// Generator: https://pub.dev/packages/dimengen
// Author: http://github.com/warioddly
// --------------------------------------------------
//

part of 'dimensions.dart';

// **************************************************************************
// InsetsGenerator
// **************************************************************************

abstract class Insets {
  const Insets._();

  static const EdgeInsets zero = EdgeInsets.all(0.0);
  static const EdgeInsets zeroTop = EdgeInsets.only(top: 0.0);
  static const EdgeInsets zeroBottom = EdgeInsets.only(bottom: 0.0);
  static const EdgeInsets zeroLeft = EdgeInsets.only(left: 0.0);
  static const EdgeInsets zeroRight = EdgeInsets.only(right: 0.0);
  static const EdgeInsets zeroVertical = EdgeInsets.symmetric(vertical: 0.0);
  static const EdgeInsets zeroHorizontal = EdgeInsets.symmetric(
    horizontal: 0.0,
  );
  static const EdgeInsets zeroTopXxsBottom = EdgeInsets.only(
    top: 0.0,
    bottom: 2.0,
  );
  static const EdgeInsets zeroLeftXxsRight = EdgeInsets.only(
    left: 0.0,
    right: 2.0,
  );
  static const EdgeInsets zeroTopXxsLeft = EdgeInsets.only(top: 0.0, left: 2.0);
  static const EdgeInsets zeroRightXxsBottom = EdgeInsets.only(
    right: 0.0,
    bottom: 2.0,
  );
  static const EdgeInsets zeroTopXsBottom = EdgeInsets.only(
    top: 0.0,
    bottom: 4.0,
  );
  static const EdgeInsets zeroLeftXsRight = EdgeInsets.only(
    left: 0.0,
    right: 4.0,
  );
  static const EdgeInsets zeroTopXsLeft = EdgeInsets.only(top: 0.0, left: 4.0);
  static const EdgeInsets zeroRightXsBottom = EdgeInsets.only(
    right: 0.0,
    bottom: 4.0,
  );
  static const EdgeInsets zeroTopSBottom = EdgeInsets.only(
    top: 0.0,
    bottom: 8.0,
  );
  static const EdgeInsets zeroLeftSRight = EdgeInsets.only(
    left: 0.0,
    right: 8.0,
  );
  static const EdgeInsets zeroTopSLeft = EdgeInsets.only(top: 0.0, left: 8.0);
  static const EdgeInsets zeroRightSBottom = EdgeInsets.only(
    right: 0.0,
    bottom: 8.0,
  );
  static const EdgeInsets zeroTopMBottom = EdgeInsets.only(
    top: 0.0,
    bottom: 16.0,
  );
  static const EdgeInsets zeroLeftMRight = EdgeInsets.only(
    left: 0.0,
    right: 16.0,
  );
  static const EdgeInsets zeroTopMLeft = EdgeInsets.only(top: 0.0, left: 16.0);
  static const EdgeInsets zeroRightMBottom = EdgeInsets.only(
    right: 0.0,
    bottom: 16.0,
  );
  static const EdgeInsets zeroTopLBottom = EdgeInsets.only(
    top: 0.0,
    bottom: 24.0,
  );
  static const EdgeInsets zeroLeftLRight = EdgeInsets.only(
    left: 0.0,
    right: 24.0,
  );
  static const EdgeInsets zeroTopLLeft = EdgeInsets.only(top: 0.0, left: 24.0);
  static const EdgeInsets zeroRightLBottom = EdgeInsets.only(
    right: 0.0,
    bottom: 24.0,
  );
  static const EdgeInsets zeroTopXlBottom = EdgeInsets.only(
    top: 0.0,
    bottom: 32.0,
  );
  static const EdgeInsets zeroLeftXlRight = EdgeInsets.only(
    left: 0.0,
    right: 32.0,
  );
  static const EdgeInsets zeroTopXlLeft = EdgeInsets.only(top: 0.0, left: 32.0);
  static const EdgeInsets zeroRightXlBottom = EdgeInsets.only(
    right: 0.0,
    bottom: 32.0,
  );
  static const EdgeInsets zeroTopXxlBottom = EdgeInsets.only(
    top: 0.0,
    bottom: 48.0,
  );
  static const EdgeInsets zeroLeftXxlRight = EdgeInsets.only(
    left: 0.0,
    right: 48.0,
  );
  static const EdgeInsets zeroTopXxlLeft = EdgeInsets.only(
    top: 0.0,
    left: 48.0,
  );
  static const EdgeInsets zeroRightXxlBottom = EdgeInsets.only(
    right: 0.0,
    bottom: 48.0,
  );
  static const EdgeInsets xxs = EdgeInsets.all(2.0);
  static const EdgeInsets xxsTop = EdgeInsets.only(top: 2.0);
  static const EdgeInsets xxsBottom = EdgeInsets.only(bottom: 2.0);
  static const EdgeInsets xxsLeft = EdgeInsets.only(left: 2.0);
  static const EdgeInsets xxsRight = EdgeInsets.only(right: 2.0);
  static const EdgeInsets xxsVertical = EdgeInsets.symmetric(vertical: 2.0);
  static const EdgeInsets xxsHorizontal = EdgeInsets.symmetric(horizontal: 2.0);
  static const EdgeInsets xxsTopZeroBottom = EdgeInsets.only(
    top: 2.0,
    bottom: 0.0,
  );
  static const EdgeInsets xxsLeftZeroRight = EdgeInsets.only(
    left: 2.0,
    right: 0.0,
  );
  static const EdgeInsets xxsTopZeroLeft = EdgeInsets.only(top: 2.0, left: 0.0);
  static const EdgeInsets xxsRightZeroBottom = EdgeInsets.only(
    right: 2.0,
    bottom: 0.0,
  );
  static const EdgeInsets xxsTopXsBottom = EdgeInsets.only(
    top: 2.0,
    bottom: 4.0,
  );
  static const EdgeInsets xxsLeftXsRight = EdgeInsets.only(
    left: 2.0,
    right: 4.0,
  );
  static const EdgeInsets xxsTopXsLeft = EdgeInsets.only(top: 2.0, left: 4.0);
  static const EdgeInsets xxsRightXsBottom = EdgeInsets.only(
    right: 2.0,
    bottom: 4.0,
  );
  static const EdgeInsets xxsTopSBottom = EdgeInsets.only(
    top: 2.0,
    bottom: 8.0,
  );
  static const EdgeInsets xxsLeftSRight = EdgeInsets.only(
    left: 2.0,
    right: 8.0,
  );
  static const EdgeInsets xxsTopSLeft = EdgeInsets.only(top: 2.0, left: 8.0);
  static const EdgeInsets xxsRightSBottom = EdgeInsets.only(
    right: 2.0,
    bottom: 8.0,
  );
  static const EdgeInsets xxsTopMBottom = EdgeInsets.only(
    top: 2.0,
    bottom: 16.0,
  );
  static const EdgeInsets xxsLeftMRight = EdgeInsets.only(
    left: 2.0,
    right: 16.0,
  );
  static const EdgeInsets xxsTopMLeft = EdgeInsets.only(top: 2.0, left: 16.0);
  static const EdgeInsets xxsRightMBottom = EdgeInsets.only(
    right: 2.0,
    bottom: 16.0,
  );
  static const EdgeInsets xxsTopLBottom = EdgeInsets.only(
    top: 2.0,
    bottom: 24.0,
  );
  static const EdgeInsets xxsLeftLRight = EdgeInsets.only(
    left: 2.0,
    right: 24.0,
  );
  static const EdgeInsets xxsTopLLeft = EdgeInsets.only(top: 2.0, left: 24.0);
  static const EdgeInsets xxsRightLBottom = EdgeInsets.only(
    right: 2.0,
    bottom: 24.0,
  );
  static const EdgeInsets xxsTopXlBottom = EdgeInsets.only(
    top: 2.0,
    bottom: 32.0,
  );
  static const EdgeInsets xxsLeftXlRight = EdgeInsets.only(
    left: 2.0,
    right: 32.0,
  );
  static const EdgeInsets xxsTopXlLeft = EdgeInsets.only(top: 2.0, left: 32.0);
  static const EdgeInsets xxsRightXlBottom = EdgeInsets.only(
    right: 2.0,
    bottom: 32.0,
  );
  static const EdgeInsets xxsTopXxlBottom = EdgeInsets.only(
    top: 2.0,
    bottom: 48.0,
  );
  static const EdgeInsets xxsLeftXxlRight = EdgeInsets.only(
    left: 2.0,
    right: 48.0,
  );
  static const EdgeInsets xxsTopXxlLeft = EdgeInsets.only(top: 2.0, left: 48.0);
  static const EdgeInsets xxsRightXxlBottom = EdgeInsets.only(
    right: 2.0,
    bottom: 48.0,
  );
  static const EdgeInsets xs = EdgeInsets.all(4.0);
  static const EdgeInsets xsTop = EdgeInsets.only(top: 4.0);
  static const EdgeInsets xsBottom = EdgeInsets.only(bottom: 4.0);
  static const EdgeInsets xsLeft = EdgeInsets.only(left: 4.0);
  static const EdgeInsets xsRight = EdgeInsets.only(right: 4.0);
  static const EdgeInsets xsVertical = EdgeInsets.symmetric(vertical: 4.0);
  static const EdgeInsets xsHorizontal = EdgeInsets.symmetric(horizontal: 4.0);
  static const EdgeInsets xsTopZeroBottom = EdgeInsets.only(
    top: 4.0,
    bottom: 0.0,
  );
  static const EdgeInsets xsLeftZeroRight = EdgeInsets.only(
    left: 4.0,
    right: 0.0,
  );
  static const EdgeInsets xsTopZeroLeft = EdgeInsets.only(top: 4.0, left: 0.0);
  static const EdgeInsets xsRightZeroBottom = EdgeInsets.only(
    right: 4.0,
    bottom: 0.0,
  );
  static const EdgeInsets xsTopXxsBottom = EdgeInsets.only(
    top: 4.0,
    bottom: 2.0,
  );
  static const EdgeInsets xsLeftXxsRight = EdgeInsets.only(
    left: 4.0,
    right: 2.0,
  );
  static const EdgeInsets xsTopXxsLeft = EdgeInsets.only(top: 4.0, left: 2.0);
  static const EdgeInsets xsRightXxsBottom = EdgeInsets.only(
    right: 4.0,
    bottom: 2.0,
  );
  static const EdgeInsets xsTopSBottom = EdgeInsets.only(top: 4.0, bottom: 8.0);
  static const EdgeInsets xsLeftSRight = EdgeInsets.only(left: 4.0, right: 8.0);
  static const EdgeInsets xsTopSLeft = EdgeInsets.only(top: 4.0, left: 8.0);
  static const EdgeInsets xsRightSBottom = EdgeInsets.only(
    right: 4.0,
    bottom: 8.0,
  );
  static const EdgeInsets xsTopMBottom = EdgeInsets.only(
    top: 4.0,
    bottom: 16.0,
  );
  static const EdgeInsets xsLeftMRight = EdgeInsets.only(
    left: 4.0,
    right: 16.0,
  );
  static const EdgeInsets xsTopMLeft = EdgeInsets.only(top: 4.0, left: 16.0);
  static const EdgeInsets xsRightMBottom = EdgeInsets.only(
    right: 4.0,
    bottom: 16.0,
  );
  static const EdgeInsets xsTopLBottom = EdgeInsets.only(
    top: 4.0,
    bottom: 24.0,
  );
  static const EdgeInsets xsLeftLRight = EdgeInsets.only(
    left: 4.0,
    right: 24.0,
  );
  static const EdgeInsets xsTopLLeft = EdgeInsets.only(top: 4.0, left: 24.0);
  static const EdgeInsets xsRightLBottom = EdgeInsets.only(
    right: 4.0,
    bottom: 24.0,
  );
  static const EdgeInsets xsTopXlBottom = EdgeInsets.only(
    top: 4.0,
    bottom: 32.0,
  );
  static const EdgeInsets xsLeftXlRight = EdgeInsets.only(
    left: 4.0,
    right: 32.0,
  );
  static const EdgeInsets xsTopXlLeft = EdgeInsets.only(top: 4.0, left: 32.0);
  static const EdgeInsets xsRightXlBottom = EdgeInsets.only(
    right: 4.0,
    bottom: 32.0,
  );
  static const EdgeInsets xsTopXxlBottom = EdgeInsets.only(
    top: 4.0,
    bottom: 48.0,
  );
  static const EdgeInsets xsLeftXxlRight = EdgeInsets.only(
    left: 4.0,
    right: 48.0,
  );
  static const EdgeInsets xsTopXxlLeft = EdgeInsets.only(top: 4.0, left: 48.0);
  static const EdgeInsets xsRightXxlBottom = EdgeInsets.only(
    right: 4.0,
    bottom: 48.0,
  );
  static const EdgeInsets s = EdgeInsets.all(8.0);
  static const EdgeInsets sTop = EdgeInsets.only(top: 8.0);
  static const EdgeInsets sBottom = EdgeInsets.only(bottom: 8.0);
  static const EdgeInsets sLeft = EdgeInsets.only(left: 8.0);
  static const EdgeInsets sRight = EdgeInsets.only(right: 8.0);
  static const EdgeInsets sVertical = EdgeInsets.symmetric(vertical: 8.0);
  static const EdgeInsets sHorizontal = EdgeInsets.symmetric(horizontal: 8.0);
  static const EdgeInsets sTopZeroBottom = EdgeInsets.only(
    top: 8.0,
    bottom: 0.0,
  );
  static const EdgeInsets sLeftZeroRight = EdgeInsets.only(
    left: 8.0,
    right: 0.0,
  );
  static const EdgeInsets sTopZeroLeft = EdgeInsets.only(top: 8.0, left: 0.0);
  static const EdgeInsets sRightZeroBottom = EdgeInsets.only(
    right: 8.0,
    bottom: 0.0,
  );
  static const EdgeInsets sTopXxsBottom = EdgeInsets.only(
    top: 8.0,
    bottom: 2.0,
  );
  static const EdgeInsets sLeftXxsRight = EdgeInsets.only(
    left: 8.0,
    right: 2.0,
  );
  static const EdgeInsets sTopXxsLeft = EdgeInsets.only(top: 8.0, left: 2.0);
  static const EdgeInsets sRightXxsBottom = EdgeInsets.only(
    right: 8.0,
    bottom: 2.0,
  );
  static const EdgeInsets sTopXsBottom = EdgeInsets.only(top: 8.0, bottom: 4.0);
  static const EdgeInsets sLeftXsRight = EdgeInsets.only(left: 8.0, right: 4.0);
  static const EdgeInsets sTopXsLeft = EdgeInsets.only(top: 8.0, left: 4.0);
  static const EdgeInsets sRightXsBottom = EdgeInsets.only(
    right: 8.0,
    bottom: 4.0,
  );
  static const EdgeInsets sTopMBottom = EdgeInsets.only(top: 8.0, bottom: 16.0);
  static const EdgeInsets sLeftMRight = EdgeInsets.only(left: 8.0, right: 16.0);
  static const EdgeInsets sTopMLeft = EdgeInsets.only(top: 8.0, left: 16.0);
  static const EdgeInsets sRightMBottom = EdgeInsets.only(
    right: 8.0,
    bottom: 16.0,
  );
  static const EdgeInsets sTopLBottom = EdgeInsets.only(top: 8.0, bottom: 24.0);
  static const EdgeInsets sLeftLRight = EdgeInsets.only(left: 8.0, right: 24.0);
  static const EdgeInsets sTopLLeft = EdgeInsets.only(top: 8.0, left: 24.0);
  static const EdgeInsets sRightLBottom = EdgeInsets.only(
    right: 8.0,
    bottom: 24.0,
  );
  static const EdgeInsets sTopXlBottom = EdgeInsets.only(
    top: 8.0,
    bottom: 32.0,
  );
  static const EdgeInsets sLeftXlRight = EdgeInsets.only(
    left: 8.0,
    right: 32.0,
  );
  static const EdgeInsets sTopXlLeft = EdgeInsets.only(top: 8.0, left: 32.0);
  static const EdgeInsets sRightXlBottom = EdgeInsets.only(
    right: 8.0,
    bottom: 32.0,
  );
  static const EdgeInsets sTopXxlBottom = EdgeInsets.only(
    top: 8.0,
    bottom: 48.0,
  );
  static const EdgeInsets sLeftXxlRight = EdgeInsets.only(
    left: 8.0,
    right: 48.0,
  );
  static const EdgeInsets sTopXxlLeft = EdgeInsets.only(top: 8.0, left: 48.0);
  static const EdgeInsets sRightXxlBottom = EdgeInsets.only(
    right: 8.0,
    bottom: 48.0,
  );
  static const EdgeInsets m = EdgeInsets.all(16.0);
  static const EdgeInsets mTop = EdgeInsets.only(top: 16.0);
  static const EdgeInsets mBottom = EdgeInsets.only(bottom: 16.0);
  static const EdgeInsets mLeft = EdgeInsets.only(left: 16.0);
  static const EdgeInsets mRight = EdgeInsets.only(right: 16.0);
  static const EdgeInsets mVertical = EdgeInsets.symmetric(vertical: 16.0);
  static const EdgeInsets mHorizontal = EdgeInsets.symmetric(horizontal: 16.0);
  static const EdgeInsets mTopZeroBottom = EdgeInsets.only(
    top: 16.0,
    bottom: 0.0,
  );
  static const EdgeInsets mLeftZeroRight = EdgeInsets.only(
    left: 16.0,
    right: 0.0,
  );
  static const EdgeInsets mTopZeroLeft = EdgeInsets.only(top: 16.0, left: 0.0);
  static const EdgeInsets mRightZeroBottom = EdgeInsets.only(
    right: 16.0,
    bottom: 0.0,
  );
  static const EdgeInsets mTopXxsBottom = EdgeInsets.only(
    top: 16.0,
    bottom: 2.0,
  );
  static const EdgeInsets mLeftXxsRight = EdgeInsets.only(
    left: 16.0,
    right: 2.0,
  );
  static const EdgeInsets mTopXxsLeft = EdgeInsets.only(top: 16.0, left: 2.0);
  static const EdgeInsets mRightXxsBottom = EdgeInsets.only(
    right: 16.0,
    bottom: 2.0,
  );
  static const EdgeInsets mTopXsBottom = EdgeInsets.only(
    top: 16.0,
    bottom: 4.0,
  );
  static const EdgeInsets mLeftXsRight = EdgeInsets.only(
    left: 16.0,
    right: 4.0,
  );
  static const EdgeInsets mTopXsLeft = EdgeInsets.only(top: 16.0, left: 4.0);
  static const EdgeInsets mRightXsBottom = EdgeInsets.only(
    right: 16.0,
    bottom: 4.0,
  );
  static const EdgeInsets mTopSBottom = EdgeInsets.only(top: 16.0, bottom: 8.0);
  static const EdgeInsets mLeftSRight = EdgeInsets.only(left: 16.0, right: 8.0);
  static const EdgeInsets mTopSLeft = EdgeInsets.only(top: 16.0, left: 8.0);
  static const EdgeInsets mRightSBottom = EdgeInsets.only(
    right: 16.0,
    bottom: 8.0,
  );
  static const EdgeInsets mTopLBottom = EdgeInsets.only(
    top: 16.0,
    bottom: 24.0,
  );
  static const EdgeInsets mLeftLRight = EdgeInsets.only(
    left: 16.0,
    right: 24.0,
  );
  static const EdgeInsets mTopLLeft = EdgeInsets.only(top: 16.0, left: 24.0);
  static const EdgeInsets mRightLBottom = EdgeInsets.only(
    right: 16.0,
    bottom: 24.0,
  );
  static const EdgeInsets mTopXlBottom = EdgeInsets.only(
    top: 16.0,
    bottom: 32.0,
  );
  static const EdgeInsets mLeftXlRight = EdgeInsets.only(
    left: 16.0,
    right: 32.0,
  );
  static const EdgeInsets mTopXlLeft = EdgeInsets.only(top: 16.0, left: 32.0);
  static const EdgeInsets mRightXlBottom = EdgeInsets.only(
    right: 16.0,
    bottom: 32.0,
  );
  static const EdgeInsets mTopXxlBottom = EdgeInsets.only(
    top: 16.0,
    bottom: 48.0,
  );
  static const EdgeInsets mLeftXxlRight = EdgeInsets.only(
    left: 16.0,
    right: 48.0,
  );
  static const EdgeInsets mTopXxlLeft = EdgeInsets.only(top: 16.0, left: 48.0);
  static const EdgeInsets mRightXxlBottom = EdgeInsets.only(
    right: 16.0,
    bottom: 48.0,
  );
  static const EdgeInsets l = EdgeInsets.all(24.0);
  static const EdgeInsets lTop = EdgeInsets.only(top: 24.0);
  static const EdgeInsets lBottom = EdgeInsets.only(bottom: 24.0);
  static const EdgeInsets lLeft = EdgeInsets.only(left: 24.0);
  static const EdgeInsets lRight = EdgeInsets.only(right: 24.0);
  static const EdgeInsets lVertical = EdgeInsets.symmetric(vertical: 24.0);
  static const EdgeInsets lHorizontal = EdgeInsets.symmetric(horizontal: 24.0);
  static const EdgeInsets lTopZeroBottom = EdgeInsets.only(
    top: 24.0,
    bottom: 0.0,
  );
  static const EdgeInsets lLeftZeroRight = EdgeInsets.only(
    left: 24.0,
    right: 0.0,
  );
  static const EdgeInsets lTopZeroLeft = EdgeInsets.only(top: 24.0, left: 0.0);
  static const EdgeInsets lRightZeroBottom = EdgeInsets.only(
    right: 24.0,
    bottom: 0.0,
  );
  static const EdgeInsets lTopXxsBottom = EdgeInsets.only(
    top: 24.0,
    bottom: 2.0,
  );
  static const EdgeInsets lLeftXxsRight = EdgeInsets.only(
    left: 24.0,
    right: 2.0,
  );
  static const EdgeInsets lTopXxsLeft = EdgeInsets.only(top: 24.0, left: 2.0);
  static const EdgeInsets lRightXxsBottom = EdgeInsets.only(
    right: 24.0,
    bottom: 2.0,
  );
  static const EdgeInsets lTopXsBottom = EdgeInsets.only(
    top: 24.0,
    bottom: 4.0,
  );
  static const EdgeInsets lLeftXsRight = EdgeInsets.only(
    left: 24.0,
    right: 4.0,
  );
  static const EdgeInsets lTopXsLeft = EdgeInsets.only(top: 24.0, left: 4.0);
  static const EdgeInsets lRightXsBottom = EdgeInsets.only(
    right: 24.0,
    bottom: 4.0,
  );
  static const EdgeInsets lTopSBottom = EdgeInsets.only(top: 24.0, bottom: 8.0);
  static const EdgeInsets lLeftSRight = EdgeInsets.only(left: 24.0, right: 8.0);
  static const EdgeInsets lTopSLeft = EdgeInsets.only(top: 24.0, left: 8.0);
  static const EdgeInsets lRightSBottom = EdgeInsets.only(
    right: 24.0,
    bottom: 8.0,
  );
  static const EdgeInsets lTopMBottom = EdgeInsets.only(
    top: 24.0,
    bottom: 16.0,
  );
  static const EdgeInsets lLeftMRight = EdgeInsets.only(
    left: 24.0,
    right: 16.0,
  );
  static const EdgeInsets lTopMLeft = EdgeInsets.only(top: 24.0, left: 16.0);
  static const EdgeInsets lRightMBottom = EdgeInsets.only(
    right: 24.0,
    bottom: 16.0,
  );
  static const EdgeInsets lTopXlBottom = EdgeInsets.only(
    top: 24.0,
    bottom: 32.0,
  );
  static const EdgeInsets lLeftXlRight = EdgeInsets.only(
    left: 24.0,
    right: 32.0,
  );
  static const EdgeInsets lTopXlLeft = EdgeInsets.only(top: 24.0, left: 32.0);
  static const EdgeInsets lRightXlBottom = EdgeInsets.only(
    right: 24.0,
    bottom: 32.0,
  );
  static const EdgeInsets lTopXxlBottom = EdgeInsets.only(
    top: 24.0,
    bottom: 48.0,
  );
  static const EdgeInsets lLeftXxlRight = EdgeInsets.only(
    left: 24.0,
    right: 48.0,
  );
  static const EdgeInsets lTopXxlLeft = EdgeInsets.only(top: 24.0, left: 48.0);
  static const EdgeInsets lRightXxlBottom = EdgeInsets.only(
    right: 24.0,
    bottom: 48.0,
  );
  static const EdgeInsets xl = EdgeInsets.all(32.0);
  static const EdgeInsets xlTop = EdgeInsets.only(top: 32.0);
  static const EdgeInsets xlBottom = EdgeInsets.only(bottom: 32.0);
  static const EdgeInsets xlLeft = EdgeInsets.only(left: 32.0);
  static const EdgeInsets xlRight = EdgeInsets.only(right: 32.0);
  static const EdgeInsets xlVertical = EdgeInsets.symmetric(vertical: 32.0);
  static const EdgeInsets xlHorizontal = EdgeInsets.symmetric(horizontal: 32.0);
  static const EdgeInsets xlTopZeroBottom = EdgeInsets.only(
    top: 32.0,
    bottom: 0.0,
  );
  static const EdgeInsets xlLeftZeroRight = EdgeInsets.only(
    left: 32.0,
    right: 0.0,
  );
  static const EdgeInsets xlTopZeroLeft = EdgeInsets.only(top: 32.0, left: 0.0);
  static const EdgeInsets xlRightZeroBottom = EdgeInsets.only(
    right: 32.0,
    bottom: 0.0,
  );
  static const EdgeInsets xlTopXxsBottom = EdgeInsets.only(
    top: 32.0,
    bottom: 2.0,
  );
  static const EdgeInsets xlLeftXxsRight = EdgeInsets.only(
    left: 32.0,
    right: 2.0,
  );
  static const EdgeInsets xlTopXxsLeft = EdgeInsets.only(top: 32.0, left: 2.0);
  static const EdgeInsets xlRightXxsBottom = EdgeInsets.only(
    right: 32.0,
    bottom: 2.0,
  );
  static const EdgeInsets xlTopXsBottom = EdgeInsets.only(
    top: 32.0,
    bottom: 4.0,
  );
  static const EdgeInsets xlLeftXsRight = EdgeInsets.only(
    left: 32.0,
    right: 4.0,
  );
  static const EdgeInsets xlTopXsLeft = EdgeInsets.only(top: 32.0, left: 4.0);
  static const EdgeInsets xlRightXsBottom = EdgeInsets.only(
    right: 32.0,
    bottom: 4.0,
  );
  static const EdgeInsets xlTopSBottom = EdgeInsets.only(
    top: 32.0,
    bottom: 8.0,
  );
  static const EdgeInsets xlLeftSRight = EdgeInsets.only(
    left: 32.0,
    right: 8.0,
  );
  static const EdgeInsets xlTopSLeft = EdgeInsets.only(top: 32.0, left: 8.0);
  static const EdgeInsets xlRightSBottom = EdgeInsets.only(
    right: 32.0,
    bottom: 8.0,
  );
  static const EdgeInsets xlTopMBottom = EdgeInsets.only(
    top: 32.0,
    bottom: 16.0,
  );
  static const EdgeInsets xlLeftMRight = EdgeInsets.only(
    left: 32.0,
    right: 16.0,
  );
  static const EdgeInsets xlTopMLeft = EdgeInsets.only(top: 32.0, left: 16.0);
  static const EdgeInsets xlRightMBottom = EdgeInsets.only(
    right: 32.0,
    bottom: 16.0,
  );
  static const EdgeInsets xlTopLBottom = EdgeInsets.only(
    top: 32.0,
    bottom: 24.0,
  );
  static const EdgeInsets xlLeftLRight = EdgeInsets.only(
    left: 32.0,
    right: 24.0,
  );
  static const EdgeInsets xlTopLLeft = EdgeInsets.only(top: 32.0, left: 24.0);
  static const EdgeInsets xlRightLBottom = EdgeInsets.only(
    right: 32.0,
    bottom: 24.0,
  );
  static const EdgeInsets xlTopXxlBottom = EdgeInsets.only(
    top: 32.0,
    bottom: 48.0,
  );
  static const EdgeInsets xlLeftXxlRight = EdgeInsets.only(
    left: 32.0,
    right: 48.0,
  );
  static const EdgeInsets xlTopXxlLeft = EdgeInsets.only(top: 32.0, left: 48.0);
  static const EdgeInsets xlRightXxlBottom = EdgeInsets.only(
    right: 32.0,
    bottom: 48.0,
  );
  static const EdgeInsets xxl = EdgeInsets.all(48.0);
  static const EdgeInsets xxlTop = EdgeInsets.only(top: 48.0);
  static const EdgeInsets xxlBottom = EdgeInsets.only(bottom: 48.0);
  static const EdgeInsets xxlLeft = EdgeInsets.only(left: 48.0);
  static const EdgeInsets xxlRight = EdgeInsets.only(right: 48.0);
  static const EdgeInsets xxlVertical = EdgeInsets.symmetric(vertical: 48.0);
  static const EdgeInsets xxlHorizontal = EdgeInsets.symmetric(
    horizontal: 48.0,
  );
  static const EdgeInsets xxlTopZeroBottom = EdgeInsets.only(
    top: 48.0,
    bottom: 0.0,
  );
  static const EdgeInsets xxlLeftZeroRight = EdgeInsets.only(
    left: 48.0,
    right: 0.0,
  );
  static const EdgeInsets xxlTopZeroLeft = EdgeInsets.only(
    top: 48.0,
    left: 0.0,
  );
  static const EdgeInsets xxlRightZeroBottom = EdgeInsets.only(
    right: 48.0,
    bottom: 0.0,
  );
  static const EdgeInsets xxlTopXxsBottom = EdgeInsets.only(
    top: 48.0,
    bottom: 2.0,
  );
  static const EdgeInsets xxlLeftXxsRight = EdgeInsets.only(
    left: 48.0,
    right: 2.0,
  );
  static const EdgeInsets xxlTopXxsLeft = EdgeInsets.only(top: 48.0, left: 2.0);
  static const EdgeInsets xxlRightXxsBottom = EdgeInsets.only(
    right: 48.0,
    bottom: 2.0,
  );
  static const EdgeInsets xxlTopXsBottom = EdgeInsets.only(
    top: 48.0,
    bottom: 4.0,
  );
  static const EdgeInsets xxlLeftXsRight = EdgeInsets.only(
    left: 48.0,
    right: 4.0,
  );
  static const EdgeInsets xxlTopXsLeft = EdgeInsets.only(top: 48.0, left: 4.0);
  static const EdgeInsets xxlRightXsBottom = EdgeInsets.only(
    right: 48.0,
    bottom: 4.0,
  );
  static const EdgeInsets xxlTopSBottom = EdgeInsets.only(
    top: 48.0,
    bottom: 8.0,
  );
  static const EdgeInsets xxlLeftSRight = EdgeInsets.only(
    left: 48.0,
    right: 8.0,
  );
  static const EdgeInsets xxlTopSLeft = EdgeInsets.only(top: 48.0, left: 8.0);
  static const EdgeInsets xxlRightSBottom = EdgeInsets.only(
    right: 48.0,
    bottom: 8.0,
  );
  static const EdgeInsets xxlTopMBottom = EdgeInsets.only(
    top: 48.0,
    bottom: 16.0,
  );
  static const EdgeInsets xxlLeftMRight = EdgeInsets.only(
    left: 48.0,
    right: 16.0,
  );
  static const EdgeInsets xxlTopMLeft = EdgeInsets.only(top: 48.0, left: 16.0);
  static const EdgeInsets xxlRightMBottom = EdgeInsets.only(
    right: 48.0,
    bottom: 16.0,
  );
  static const EdgeInsets xxlTopLBottom = EdgeInsets.only(
    top: 48.0,
    bottom: 24.0,
  );
  static const EdgeInsets xxlLeftLRight = EdgeInsets.only(
    left: 48.0,
    right: 24.0,
  );
  static const EdgeInsets xxlTopLLeft = EdgeInsets.only(top: 48.0, left: 24.0);
  static const EdgeInsets xxlRightLBottom = EdgeInsets.only(
    right: 48.0,
    bottom: 24.0,
  );
  static const EdgeInsets xxlTopXlBottom = EdgeInsets.only(
    top: 48.0,
    bottom: 32.0,
  );
  static const EdgeInsets xxlLeftXlRight = EdgeInsets.only(
    left: 48.0,
    right: 32.0,
  );
  static const EdgeInsets xxlTopXlLeft = EdgeInsets.only(top: 48.0, left: 32.0);
  static const EdgeInsets xxlRightXlBottom = EdgeInsets.only(
    right: 48.0,
    bottom: 32.0,
  );
}

// **************************************************************************
// SpacesGenerator
// **************************************************************************

abstract class Spaces {
  const Spaces._();

  static const SizedBox zero = SizedBox.square(dimension: 0.0);
  static const SizedBox zeroVertical = SizedBox(height: 0.0);
  static const SizedBox zeroHorizontal = SizedBox(width: 0.0);
  static const SizedBox xxs = SizedBox.square(dimension: 2.0);
  static const SizedBox xxsVertical = SizedBox(height: 2.0);
  static const SizedBox xxsHorizontal = SizedBox(width: 2.0);
  static const SizedBox xs = SizedBox.square(dimension: 4.0);
  static const SizedBox xsVertical = SizedBox(height: 4.0);
  static const SizedBox xsHorizontal = SizedBox(width: 4.0);
  static const SizedBox s = SizedBox.square(dimension: 8.0);
  static const SizedBox sVertical = SizedBox(height: 8.0);
  static const SizedBox sHorizontal = SizedBox(width: 8.0);
  static const SizedBox m = SizedBox.square(dimension: 16.0);
  static const SizedBox mVertical = SizedBox(height: 16.0);
  static const SizedBox mHorizontal = SizedBox(width: 16.0);
  static const SizedBox l = SizedBox.square(dimension: 24.0);
  static const SizedBox lVertical = SizedBox(height: 24.0);
  static const SizedBox lHorizontal = SizedBox(width: 24.0);
  static const SizedBox xl = SizedBox.square(dimension: 32.0);
  static const SizedBox xlVertical = SizedBox(height: 32.0);
  static const SizedBox xlHorizontal = SizedBox(width: 32.0);
  static const SizedBox xxl = SizedBox.square(dimension: 48.0);
  static const SizedBox xxlVertical = SizedBox(height: 48.0);
  static const SizedBox xxlHorizontal = SizedBox(width: 48.0);
  static SizedBox h(double value) => SizedBox(height: value);
  static SizedBox w(double value) => SizedBox(width: value);
}

// **************************************************************************
// BorderRadiusGenerator
// **************************************************************************

abstract class RadiusDimensions {
  const RadiusDimensions._();

  static const BorderRadius zero = BorderRadius.all(Radius.circular(0.0));
  static const BorderRadius zeroTop = BorderRadius.only(
    topLeft: Radius.circular(0.0),
    topRight: Radius.circular(0.0),
  );
  static const BorderRadius zeroBottom = BorderRadius.only(
    bottomLeft: Radius.circular(0.0),
    bottomRight: Radius.circular(0.0),
  );
  static const BorderRadius zeroLeft = BorderRadius.only(
    topLeft: Radius.circular(0.0),
    bottomLeft: Radius.circular(0.0),
  );
  static const BorderRadius zeroRight = BorderRadius.only(
    topRight: Radius.circular(0.0),
    bottomRight: Radius.circular(0.0),
  );
  static const BorderRadius zeroVertical = BorderRadius.vertical(
    top: Radius.circular(0.0),
    bottom: Radius.circular(0.0),
  );
  static const BorderRadius zeroHorizontal = BorderRadius.horizontal(
    left: Radius.circular(0.0),
    right: Radius.circular(0.0),
  );
  static const BorderRadius zeroTopLeft = BorderRadius.only(
    topLeft: Radius.circular(0.0),
  );
  static const BorderRadius zeroTopRight = BorderRadius.only(
    topRight: Radius.circular(0.0),
  );
  static const BorderRadius zeroBottomLeft = BorderRadius.only(
    bottomLeft: Radius.circular(0.0),
  );
  static const BorderRadius zeroBottomRight = BorderRadius.only(
    bottomRight: Radius.circular(0.0),
  );
  static const BorderRadius zeroTopLeftBottomRight = BorderRadius.only(
    topLeft: Radius.circular(0.0),
    bottomRight: Radius.circular(0.0),
  );
  static const BorderRadius zeroTopRightBottomLeft = BorderRadius.only(
    topRight: Radius.circular(0.0),
    bottomLeft: Radius.circular(0.0),
  );
  static const BorderRadius zeroTopXxsLeft = BorderRadius.only(
    topLeft: Radius.circular(0.0),
    topRight: Radius.circular(2.0),
  );
  static const BorderRadius zeroRightXxsBottom = BorderRadius.only(
    topRight: Radius.circular(0.0),
    bottomLeft: Radius.circular(2.0),
  );
  static const BorderRadius zeroTopXxsRight = BorderRadius.only(
    topLeft: Radius.circular(0.0),
    bottomRight: Radius.circular(2.0),
  );
  static const BorderRadius zeroBottomXxsBottom = BorderRadius.only(
    bottomLeft: Radius.circular(0.0),
    bottomRight: Radius.circular(2.0),
  );
  static const BorderRadius zeroTopXsLeft = BorderRadius.only(
    topLeft: Radius.circular(0.0),
    topRight: Radius.circular(4.0),
  );
  static const BorderRadius zeroRightXsBottom = BorderRadius.only(
    topRight: Radius.circular(0.0),
    bottomLeft: Radius.circular(4.0),
  );
  static const BorderRadius zeroTopXsRight = BorderRadius.only(
    topLeft: Radius.circular(0.0),
    bottomRight: Radius.circular(4.0),
  );
  static const BorderRadius zeroBottomXsBottom = BorderRadius.only(
    bottomLeft: Radius.circular(0.0),
    bottomRight: Radius.circular(4.0),
  );
  static const BorderRadius zeroTopSLeft = BorderRadius.only(
    topLeft: Radius.circular(0.0),
    topRight: Radius.circular(8.0),
  );
  static const BorderRadius zeroRightSBottom = BorderRadius.only(
    topRight: Radius.circular(0.0),
    bottomLeft: Radius.circular(8.0),
  );
  static const BorderRadius zeroTopSRight = BorderRadius.only(
    topLeft: Radius.circular(0.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius zeroBottomSBottom = BorderRadius.only(
    bottomLeft: Radius.circular(0.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius zeroTopMLeft = BorderRadius.only(
    topLeft: Radius.circular(0.0),
    topRight: Radius.circular(16.0),
  );
  static const BorderRadius zeroRightMBottom = BorderRadius.only(
    topRight: Radius.circular(0.0),
    bottomLeft: Radius.circular(16.0),
  );
  static const BorderRadius zeroTopMRight = BorderRadius.only(
    topLeft: Radius.circular(0.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius zeroBottomMBottom = BorderRadius.only(
    bottomLeft: Radius.circular(0.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius zeroTopLLeft = BorderRadius.only(
    topLeft: Radius.circular(0.0),
    topRight: Radius.circular(24.0),
  );
  static const BorderRadius zeroRightLBottom = BorderRadius.only(
    topRight: Radius.circular(0.0),
    bottomLeft: Radius.circular(24.0),
  );
  static const BorderRadius zeroTopLRight = BorderRadius.only(
    topLeft: Radius.circular(0.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius zeroBottomLBottom = BorderRadius.only(
    bottomLeft: Radius.circular(0.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius zeroTopXlLeft = BorderRadius.only(
    topLeft: Radius.circular(0.0),
    topRight: Radius.circular(32.0),
  );
  static const BorderRadius zeroRightXlBottom = BorderRadius.only(
    topRight: Radius.circular(0.0),
    bottomLeft: Radius.circular(32.0),
  );
  static const BorderRadius zeroTopXlRight = BorderRadius.only(
    topLeft: Radius.circular(0.0),
    bottomRight: Radius.circular(32.0),
  );
  static const BorderRadius zeroBottomXlBottom = BorderRadius.only(
    bottomLeft: Radius.circular(0.0),
    bottomRight: Radius.circular(32.0),
  );
  static const BorderRadius zeroTopXxlLeft = BorderRadius.only(
    topLeft: Radius.circular(0.0),
    topRight: Radius.circular(48.0),
  );
  static const BorderRadius zeroRightXxlBottom = BorderRadius.only(
    topRight: Radius.circular(0.0),
    bottomLeft: Radius.circular(48.0),
  );
  static const BorderRadius zeroTopXxlRight = BorderRadius.only(
    topLeft: Radius.circular(0.0),
    bottomRight: Radius.circular(48.0),
  );
  static const BorderRadius zeroBottomXxlBottom = BorderRadius.only(
    bottomLeft: Radius.circular(0.0),
    bottomRight: Radius.circular(48.0),
  );
  static const BorderRadius xxs = BorderRadius.all(Radius.circular(2.0));
  static const BorderRadius xxsTop = BorderRadius.only(
    topLeft: Radius.circular(2.0),
    topRight: Radius.circular(2.0),
  );
  static const BorderRadius xxsBottom = BorderRadius.only(
    bottomLeft: Radius.circular(2.0),
    bottomRight: Radius.circular(2.0),
  );
  static const BorderRadius xxsLeft = BorderRadius.only(
    topLeft: Radius.circular(2.0),
    bottomLeft: Radius.circular(2.0),
  );
  static const BorderRadius xxsRight = BorderRadius.only(
    topRight: Radius.circular(2.0),
    bottomRight: Radius.circular(2.0),
  );
  static const BorderRadius xxsVertical = BorderRadius.vertical(
    top: Radius.circular(2.0),
    bottom: Radius.circular(2.0),
  );
  static const BorderRadius xxsHorizontal = BorderRadius.horizontal(
    left: Radius.circular(2.0),
    right: Radius.circular(2.0),
  );
  static const BorderRadius xxsTopLeft = BorderRadius.only(
    topLeft: Radius.circular(2.0),
  );
  static const BorderRadius xxsTopRight = BorderRadius.only(
    topRight: Radius.circular(2.0),
  );
  static const BorderRadius xxsBottomLeft = BorderRadius.only(
    bottomLeft: Radius.circular(2.0),
  );
  static const BorderRadius xxsBottomRight = BorderRadius.only(
    bottomRight: Radius.circular(2.0),
  );
  static const BorderRadius xxsTopLeftBottomRight = BorderRadius.only(
    topLeft: Radius.circular(2.0),
    bottomRight: Radius.circular(2.0),
  );
  static const BorderRadius xxsTopRightBottomLeft = BorderRadius.only(
    topRight: Radius.circular(2.0),
    bottomLeft: Radius.circular(2.0),
  );
  static const BorderRadius xxsTopZeroLeft = BorderRadius.only(
    topLeft: Radius.circular(2.0),
    topRight: Radius.circular(0.0),
  );
  static const BorderRadius xxsRightZeroBottom = BorderRadius.only(
    topRight: Radius.circular(2.0),
    bottomLeft: Radius.circular(0.0),
  );
  static const BorderRadius xxsTopZeroRight = BorderRadius.only(
    topLeft: Radius.circular(2.0),
    bottomRight: Radius.circular(0.0),
  );
  static const BorderRadius xxsBottomZeroBottom = BorderRadius.only(
    bottomLeft: Radius.circular(2.0),
    bottomRight: Radius.circular(0.0),
  );
  static const BorderRadius xxsTopXsLeft = BorderRadius.only(
    topLeft: Radius.circular(2.0),
    topRight: Radius.circular(4.0),
  );
  static const BorderRadius xxsRightXsBottom = BorderRadius.only(
    topRight: Radius.circular(2.0),
    bottomLeft: Radius.circular(4.0),
  );
  static const BorderRadius xxsTopXsRight = BorderRadius.only(
    topLeft: Radius.circular(2.0),
    bottomRight: Radius.circular(4.0),
  );
  static const BorderRadius xxsBottomXsBottom = BorderRadius.only(
    bottomLeft: Radius.circular(2.0),
    bottomRight: Radius.circular(4.0),
  );
  static const BorderRadius xxsTopSLeft = BorderRadius.only(
    topLeft: Radius.circular(2.0),
    topRight: Radius.circular(8.0),
  );
  static const BorderRadius xxsRightSBottom = BorderRadius.only(
    topRight: Radius.circular(2.0),
    bottomLeft: Radius.circular(8.0),
  );
  static const BorderRadius xxsTopSRight = BorderRadius.only(
    topLeft: Radius.circular(2.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius xxsBottomSBottom = BorderRadius.only(
    bottomLeft: Radius.circular(2.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius xxsTopMLeft = BorderRadius.only(
    topLeft: Radius.circular(2.0),
    topRight: Radius.circular(16.0),
  );
  static const BorderRadius xxsRightMBottom = BorderRadius.only(
    topRight: Radius.circular(2.0),
    bottomLeft: Radius.circular(16.0),
  );
  static const BorderRadius xxsTopMRight = BorderRadius.only(
    topLeft: Radius.circular(2.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius xxsBottomMBottom = BorderRadius.only(
    bottomLeft: Radius.circular(2.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius xxsTopLLeft = BorderRadius.only(
    topLeft: Radius.circular(2.0),
    topRight: Radius.circular(24.0),
  );
  static const BorderRadius xxsRightLBottom = BorderRadius.only(
    topRight: Radius.circular(2.0),
    bottomLeft: Radius.circular(24.0),
  );
  static const BorderRadius xxsTopLRight = BorderRadius.only(
    topLeft: Radius.circular(2.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius xxsBottomLBottom = BorderRadius.only(
    bottomLeft: Radius.circular(2.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius xxsTopXlLeft = BorderRadius.only(
    topLeft: Radius.circular(2.0),
    topRight: Radius.circular(32.0),
  );
  static const BorderRadius xxsRightXlBottom = BorderRadius.only(
    topRight: Radius.circular(2.0),
    bottomLeft: Radius.circular(32.0),
  );
  static const BorderRadius xxsTopXlRight = BorderRadius.only(
    topLeft: Radius.circular(2.0),
    bottomRight: Radius.circular(32.0),
  );
  static const BorderRadius xxsBottomXlBottom = BorderRadius.only(
    bottomLeft: Radius.circular(2.0),
    bottomRight: Radius.circular(32.0),
  );
  static const BorderRadius xxsTopXxlLeft = BorderRadius.only(
    topLeft: Radius.circular(2.0),
    topRight: Radius.circular(48.0),
  );
  static const BorderRadius xxsRightXxlBottom = BorderRadius.only(
    topRight: Radius.circular(2.0),
    bottomLeft: Radius.circular(48.0),
  );
  static const BorderRadius xxsTopXxlRight = BorderRadius.only(
    topLeft: Radius.circular(2.0),
    bottomRight: Radius.circular(48.0),
  );
  static const BorderRadius xxsBottomXxlBottom = BorderRadius.only(
    bottomLeft: Radius.circular(2.0),
    bottomRight: Radius.circular(48.0),
  );
  static const BorderRadius xs = BorderRadius.all(Radius.circular(4.0));
  static const BorderRadius xsTop = BorderRadius.only(
    topLeft: Radius.circular(4.0),
    topRight: Radius.circular(4.0),
  );
  static const BorderRadius xsBottom = BorderRadius.only(
    bottomLeft: Radius.circular(4.0),
    bottomRight: Radius.circular(4.0),
  );
  static const BorderRadius xsLeft = BorderRadius.only(
    topLeft: Radius.circular(4.0),
    bottomLeft: Radius.circular(4.0),
  );
  static const BorderRadius xsRight = BorderRadius.only(
    topRight: Radius.circular(4.0),
    bottomRight: Radius.circular(4.0),
  );
  static const BorderRadius xsVertical = BorderRadius.vertical(
    top: Radius.circular(4.0),
    bottom: Radius.circular(4.0),
  );
  static const BorderRadius xsHorizontal = BorderRadius.horizontal(
    left: Radius.circular(4.0),
    right: Radius.circular(4.0),
  );
  static const BorderRadius xsTopLeft = BorderRadius.only(
    topLeft: Radius.circular(4.0),
  );
  static const BorderRadius xsTopRight = BorderRadius.only(
    topRight: Radius.circular(4.0),
  );
  static const BorderRadius xsBottomLeft = BorderRadius.only(
    bottomLeft: Radius.circular(4.0),
  );
  static const BorderRadius xsBottomRight = BorderRadius.only(
    bottomRight: Radius.circular(4.0),
  );
  static const BorderRadius xsTopLeftBottomRight = BorderRadius.only(
    topLeft: Radius.circular(4.0),
    bottomRight: Radius.circular(4.0),
  );
  static const BorderRadius xsTopRightBottomLeft = BorderRadius.only(
    topRight: Radius.circular(4.0),
    bottomLeft: Radius.circular(4.0),
  );
  static const BorderRadius xsTopZeroLeft = BorderRadius.only(
    topLeft: Radius.circular(4.0),
    topRight: Radius.circular(0.0),
  );
  static const BorderRadius xsRightZeroBottom = BorderRadius.only(
    topRight: Radius.circular(4.0),
    bottomLeft: Radius.circular(0.0),
  );
  static const BorderRadius xsTopZeroRight = BorderRadius.only(
    topLeft: Radius.circular(4.0),
    bottomRight: Radius.circular(0.0),
  );
  static const BorderRadius xsBottomZeroBottom = BorderRadius.only(
    bottomLeft: Radius.circular(4.0),
    bottomRight: Radius.circular(0.0),
  );
  static const BorderRadius xsTopXxsLeft = BorderRadius.only(
    topLeft: Radius.circular(4.0),
    topRight: Radius.circular(2.0),
  );
  static const BorderRadius xsRightXxsBottom = BorderRadius.only(
    topRight: Radius.circular(4.0),
    bottomLeft: Radius.circular(2.0),
  );
  static const BorderRadius xsTopXxsRight = BorderRadius.only(
    topLeft: Radius.circular(4.0),
    bottomRight: Radius.circular(2.0),
  );
  static const BorderRadius xsBottomXxsBottom = BorderRadius.only(
    bottomLeft: Radius.circular(4.0),
    bottomRight: Radius.circular(2.0),
  );
  static const BorderRadius xsTopSLeft = BorderRadius.only(
    topLeft: Radius.circular(4.0),
    topRight: Radius.circular(8.0),
  );
  static const BorderRadius xsRightSBottom = BorderRadius.only(
    topRight: Radius.circular(4.0),
    bottomLeft: Radius.circular(8.0),
  );
  static const BorderRadius xsTopSRight = BorderRadius.only(
    topLeft: Radius.circular(4.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius xsBottomSBottom = BorderRadius.only(
    bottomLeft: Radius.circular(4.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius xsTopMLeft = BorderRadius.only(
    topLeft: Radius.circular(4.0),
    topRight: Radius.circular(16.0),
  );
  static const BorderRadius xsRightMBottom = BorderRadius.only(
    topRight: Radius.circular(4.0),
    bottomLeft: Radius.circular(16.0),
  );
  static const BorderRadius xsTopMRight = BorderRadius.only(
    topLeft: Radius.circular(4.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius xsBottomMBottom = BorderRadius.only(
    bottomLeft: Radius.circular(4.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius xsTopLLeft = BorderRadius.only(
    topLeft: Radius.circular(4.0),
    topRight: Radius.circular(24.0),
  );
  static const BorderRadius xsRightLBottom = BorderRadius.only(
    topRight: Radius.circular(4.0),
    bottomLeft: Radius.circular(24.0),
  );
  static const BorderRadius xsTopLRight = BorderRadius.only(
    topLeft: Radius.circular(4.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius xsBottomLBottom = BorderRadius.only(
    bottomLeft: Radius.circular(4.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius xsTopXlLeft = BorderRadius.only(
    topLeft: Radius.circular(4.0),
    topRight: Radius.circular(32.0),
  );
  static const BorderRadius xsRightXlBottom = BorderRadius.only(
    topRight: Radius.circular(4.0),
    bottomLeft: Radius.circular(32.0),
  );
  static const BorderRadius xsTopXlRight = BorderRadius.only(
    topLeft: Radius.circular(4.0),
    bottomRight: Radius.circular(32.0),
  );
  static const BorderRadius xsBottomXlBottom = BorderRadius.only(
    bottomLeft: Radius.circular(4.0),
    bottomRight: Radius.circular(32.0),
  );
  static const BorderRadius xsTopXxlLeft = BorderRadius.only(
    topLeft: Radius.circular(4.0),
    topRight: Radius.circular(48.0),
  );
  static const BorderRadius xsRightXxlBottom = BorderRadius.only(
    topRight: Radius.circular(4.0),
    bottomLeft: Radius.circular(48.0),
  );
  static const BorderRadius xsTopXxlRight = BorderRadius.only(
    topLeft: Radius.circular(4.0),
    bottomRight: Radius.circular(48.0),
  );
  static const BorderRadius xsBottomXxlBottom = BorderRadius.only(
    bottomLeft: Radius.circular(4.0),
    bottomRight: Radius.circular(48.0),
  );
  static const BorderRadius s = BorderRadius.all(Radius.circular(8.0));
  static const BorderRadius sTop = BorderRadius.only(
    topLeft: Radius.circular(8.0),
    topRight: Radius.circular(8.0),
  );
  static const BorderRadius sBottom = BorderRadius.only(
    bottomLeft: Radius.circular(8.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius sLeft = BorderRadius.only(
    topLeft: Radius.circular(8.0),
    bottomLeft: Radius.circular(8.0),
  );
  static const BorderRadius sRight = BorderRadius.only(
    topRight: Radius.circular(8.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius sVertical = BorderRadius.vertical(
    top: Radius.circular(8.0),
    bottom: Radius.circular(8.0),
  );
  static const BorderRadius sHorizontal = BorderRadius.horizontal(
    left: Radius.circular(8.0),
    right: Radius.circular(8.0),
  );
  static const BorderRadius sTopLeft = BorderRadius.only(
    topLeft: Radius.circular(8.0),
  );
  static const BorderRadius sTopRight = BorderRadius.only(
    topRight: Radius.circular(8.0),
  );
  static const BorderRadius sBottomLeft = BorderRadius.only(
    bottomLeft: Radius.circular(8.0),
  );
  static const BorderRadius sBottomRight = BorderRadius.only(
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius sTopLeftBottomRight = BorderRadius.only(
    topLeft: Radius.circular(8.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius sTopRightBottomLeft = BorderRadius.only(
    topRight: Radius.circular(8.0),
    bottomLeft: Radius.circular(8.0),
  );
  static const BorderRadius sTopZeroLeft = BorderRadius.only(
    topLeft: Radius.circular(8.0),
    topRight: Radius.circular(0.0),
  );
  static const BorderRadius sRightZeroBottom = BorderRadius.only(
    topRight: Radius.circular(8.0),
    bottomLeft: Radius.circular(0.0),
  );
  static const BorderRadius sTopZeroRight = BorderRadius.only(
    topLeft: Radius.circular(8.0),
    bottomRight: Radius.circular(0.0),
  );
  static const BorderRadius sBottomZeroBottom = BorderRadius.only(
    bottomLeft: Radius.circular(8.0),
    bottomRight: Radius.circular(0.0),
  );
  static const BorderRadius sTopXxsLeft = BorderRadius.only(
    topLeft: Radius.circular(8.0),
    topRight: Radius.circular(2.0),
  );
  static const BorderRadius sRightXxsBottom = BorderRadius.only(
    topRight: Radius.circular(8.0),
    bottomLeft: Radius.circular(2.0),
  );
  static const BorderRadius sTopXxsRight = BorderRadius.only(
    topLeft: Radius.circular(8.0),
    bottomRight: Radius.circular(2.0),
  );
  static const BorderRadius sBottomXxsBottom = BorderRadius.only(
    bottomLeft: Radius.circular(8.0),
    bottomRight: Radius.circular(2.0),
  );
  static const BorderRadius sTopXsLeft = BorderRadius.only(
    topLeft: Radius.circular(8.0),
    topRight: Radius.circular(4.0),
  );
  static const BorderRadius sRightXsBottom = BorderRadius.only(
    topRight: Radius.circular(8.0),
    bottomLeft: Radius.circular(4.0),
  );
  static const BorderRadius sTopXsRight = BorderRadius.only(
    topLeft: Radius.circular(8.0),
    bottomRight: Radius.circular(4.0),
  );
  static const BorderRadius sBottomXsBottom = BorderRadius.only(
    bottomLeft: Radius.circular(8.0),
    bottomRight: Radius.circular(4.0),
  );
  static const BorderRadius sTopMLeft = BorderRadius.only(
    topLeft: Radius.circular(8.0),
    topRight: Radius.circular(16.0),
  );
  static const BorderRadius sRightMBottom = BorderRadius.only(
    topRight: Radius.circular(8.0),
    bottomLeft: Radius.circular(16.0),
  );
  static const BorderRadius sTopMRight = BorderRadius.only(
    topLeft: Radius.circular(8.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius sBottomMBottom = BorderRadius.only(
    bottomLeft: Radius.circular(8.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius sTopLLeft = BorderRadius.only(
    topLeft: Radius.circular(8.0),
    topRight: Radius.circular(24.0),
  );
  static const BorderRadius sRightLBottom = BorderRadius.only(
    topRight: Radius.circular(8.0),
    bottomLeft: Radius.circular(24.0),
  );
  static const BorderRadius sTopLRight = BorderRadius.only(
    topLeft: Radius.circular(8.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius sBottomLBottom = BorderRadius.only(
    bottomLeft: Radius.circular(8.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius sTopXlLeft = BorderRadius.only(
    topLeft: Radius.circular(8.0),
    topRight: Radius.circular(32.0),
  );
  static const BorderRadius sRightXlBottom = BorderRadius.only(
    topRight: Radius.circular(8.0),
    bottomLeft: Radius.circular(32.0),
  );
  static const BorderRadius sTopXlRight = BorderRadius.only(
    topLeft: Radius.circular(8.0),
    bottomRight: Radius.circular(32.0),
  );
  static const BorderRadius sBottomXlBottom = BorderRadius.only(
    bottomLeft: Radius.circular(8.0),
    bottomRight: Radius.circular(32.0),
  );
  static const BorderRadius sTopXxlLeft = BorderRadius.only(
    topLeft: Radius.circular(8.0),
    topRight: Radius.circular(48.0),
  );
  static const BorderRadius sRightXxlBottom = BorderRadius.only(
    topRight: Radius.circular(8.0),
    bottomLeft: Radius.circular(48.0),
  );
  static const BorderRadius sTopXxlRight = BorderRadius.only(
    topLeft: Radius.circular(8.0),
    bottomRight: Radius.circular(48.0),
  );
  static const BorderRadius sBottomXxlBottom = BorderRadius.only(
    bottomLeft: Radius.circular(8.0),
    bottomRight: Radius.circular(48.0),
  );
  static const BorderRadius m = BorderRadius.all(Radius.circular(16.0));
  static const BorderRadius mTop = BorderRadius.only(
    topLeft: Radius.circular(16.0),
    topRight: Radius.circular(16.0),
  );
  static const BorderRadius mBottom = BorderRadius.only(
    bottomLeft: Radius.circular(16.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius mLeft = BorderRadius.only(
    topLeft: Radius.circular(16.0),
    bottomLeft: Radius.circular(16.0),
  );
  static const BorderRadius mRight = BorderRadius.only(
    topRight: Radius.circular(16.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius mVertical = BorderRadius.vertical(
    top: Radius.circular(16.0),
    bottom: Radius.circular(16.0),
  );
  static const BorderRadius mHorizontal = BorderRadius.horizontal(
    left: Radius.circular(16.0),
    right: Radius.circular(16.0),
  );
  static const BorderRadius mTopLeft = BorderRadius.only(
    topLeft: Radius.circular(16.0),
  );
  static const BorderRadius mTopRight = BorderRadius.only(
    topRight: Radius.circular(16.0),
  );
  static const BorderRadius mBottomLeft = BorderRadius.only(
    bottomLeft: Radius.circular(16.0),
  );
  static const BorderRadius mBottomRight = BorderRadius.only(
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius mTopLeftBottomRight = BorderRadius.only(
    topLeft: Radius.circular(16.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius mTopRightBottomLeft = BorderRadius.only(
    topRight: Radius.circular(16.0),
    bottomLeft: Radius.circular(16.0),
  );
  static const BorderRadius mTopZeroLeft = BorderRadius.only(
    topLeft: Radius.circular(16.0),
    topRight: Radius.circular(0.0),
  );
  static const BorderRadius mRightZeroBottom = BorderRadius.only(
    topRight: Radius.circular(16.0),
    bottomLeft: Radius.circular(0.0),
  );
  static const BorderRadius mTopZeroRight = BorderRadius.only(
    topLeft: Radius.circular(16.0),
    bottomRight: Radius.circular(0.0),
  );
  static const BorderRadius mBottomZeroBottom = BorderRadius.only(
    bottomLeft: Radius.circular(16.0),
    bottomRight: Radius.circular(0.0),
  );
  static const BorderRadius mTopXxsLeft = BorderRadius.only(
    topLeft: Radius.circular(16.0),
    topRight: Radius.circular(2.0),
  );
  static const BorderRadius mRightXxsBottom = BorderRadius.only(
    topRight: Radius.circular(16.0),
    bottomLeft: Radius.circular(2.0),
  );
  static const BorderRadius mTopXxsRight = BorderRadius.only(
    topLeft: Radius.circular(16.0),
    bottomRight: Radius.circular(2.0),
  );
  static const BorderRadius mBottomXxsBottom = BorderRadius.only(
    bottomLeft: Radius.circular(16.0),
    bottomRight: Radius.circular(2.0),
  );
  static const BorderRadius mTopXsLeft = BorderRadius.only(
    topLeft: Radius.circular(16.0),
    topRight: Radius.circular(4.0),
  );
  static const BorderRadius mRightXsBottom = BorderRadius.only(
    topRight: Radius.circular(16.0),
    bottomLeft: Radius.circular(4.0),
  );
  static const BorderRadius mTopXsRight = BorderRadius.only(
    topLeft: Radius.circular(16.0),
    bottomRight: Radius.circular(4.0),
  );
  static const BorderRadius mBottomXsBottom = BorderRadius.only(
    bottomLeft: Radius.circular(16.0),
    bottomRight: Radius.circular(4.0),
  );
  static const BorderRadius mTopSLeft = BorderRadius.only(
    topLeft: Radius.circular(16.0),
    topRight: Radius.circular(8.0),
  );
  static const BorderRadius mRightSBottom = BorderRadius.only(
    topRight: Radius.circular(16.0),
    bottomLeft: Radius.circular(8.0),
  );
  static const BorderRadius mTopSRight = BorderRadius.only(
    topLeft: Radius.circular(16.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius mBottomSBottom = BorderRadius.only(
    bottomLeft: Radius.circular(16.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius mTopLLeft = BorderRadius.only(
    topLeft: Radius.circular(16.0),
    topRight: Radius.circular(24.0),
  );
  static const BorderRadius mRightLBottom = BorderRadius.only(
    topRight: Radius.circular(16.0),
    bottomLeft: Radius.circular(24.0),
  );
  static const BorderRadius mTopLRight = BorderRadius.only(
    topLeft: Radius.circular(16.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius mBottomLBottom = BorderRadius.only(
    bottomLeft: Radius.circular(16.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius mTopXlLeft = BorderRadius.only(
    topLeft: Radius.circular(16.0),
    topRight: Radius.circular(32.0),
  );
  static const BorderRadius mRightXlBottom = BorderRadius.only(
    topRight: Radius.circular(16.0),
    bottomLeft: Radius.circular(32.0),
  );
  static const BorderRadius mTopXlRight = BorderRadius.only(
    topLeft: Radius.circular(16.0),
    bottomRight: Radius.circular(32.0),
  );
  static const BorderRadius mBottomXlBottom = BorderRadius.only(
    bottomLeft: Radius.circular(16.0),
    bottomRight: Radius.circular(32.0),
  );
  static const BorderRadius mTopXxlLeft = BorderRadius.only(
    topLeft: Radius.circular(16.0),
    topRight: Radius.circular(48.0),
  );
  static const BorderRadius mRightXxlBottom = BorderRadius.only(
    topRight: Radius.circular(16.0),
    bottomLeft: Radius.circular(48.0),
  );
  static const BorderRadius mTopXxlRight = BorderRadius.only(
    topLeft: Radius.circular(16.0),
    bottomRight: Radius.circular(48.0),
  );
  static const BorderRadius mBottomXxlBottom = BorderRadius.only(
    bottomLeft: Radius.circular(16.0),
    bottomRight: Radius.circular(48.0),
  );
  static const BorderRadius l = BorderRadius.all(Radius.circular(24.0));
  static const BorderRadius lTop = BorderRadius.only(
    topLeft: Radius.circular(24.0),
    topRight: Radius.circular(24.0),
  );
  static const BorderRadius lBottom = BorderRadius.only(
    bottomLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius lLeft = BorderRadius.only(
    topLeft: Radius.circular(24.0),
    bottomLeft: Radius.circular(24.0),
  );
  static const BorderRadius lRight = BorderRadius.only(
    topRight: Radius.circular(24.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius lVertical = BorderRadius.vertical(
    top: Radius.circular(24.0),
    bottom: Radius.circular(24.0),
  );
  static const BorderRadius lHorizontal = BorderRadius.horizontal(
    left: Radius.circular(24.0),
    right: Radius.circular(24.0),
  );
  static const BorderRadius lTopLeft = BorderRadius.only(
    topLeft: Radius.circular(24.0),
  );
  static const BorderRadius lTopRight = BorderRadius.only(
    topRight: Radius.circular(24.0),
  );
  static const BorderRadius lBottomLeft = BorderRadius.only(
    bottomLeft: Radius.circular(24.0),
  );
  static const BorderRadius lBottomRight = BorderRadius.only(
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius lTopLeftBottomRight = BorderRadius.only(
    topLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius lTopRightBottomLeft = BorderRadius.only(
    topRight: Radius.circular(24.0),
    bottomLeft: Radius.circular(24.0),
  );
  static const BorderRadius lTopZeroLeft = BorderRadius.only(
    topLeft: Radius.circular(24.0),
    topRight: Radius.circular(0.0),
  );
  static const BorderRadius lRightZeroBottom = BorderRadius.only(
    topRight: Radius.circular(24.0),
    bottomLeft: Radius.circular(0.0),
  );
  static const BorderRadius lTopZeroRight = BorderRadius.only(
    topLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(0.0),
  );
  static const BorderRadius lBottomZeroBottom = BorderRadius.only(
    bottomLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(0.0),
  );
  static const BorderRadius lTopXxsLeft = BorderRadius.only(
    topLeft: Radius.circular(24.0),
    topRight: Radius.circular(2.0),
  );
  static const BorderRadius lRightXxsBottom = BorderRadius.only(
    topRight: Radius.circular(24.0),
    bottomLeft: Radius.circular(2.0),
  );
  static const BorderRadius lTopXxsRight = BorderRadius.only(
    topLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(2.0),
  );
  static const BorderRadius lBottomXxsBottom = BorderRadius.only(
    bottomLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(2.0),
  );
  static const BorderRadius lTopXsLeft = BorderRadius.only(
    topLeft: Radius.circular(24.0),
    topRight: Radius.circular(4.0),
  );
  static const BorderRadius lRightXsBottom = BorderRadius.only(
    topRight: Radius.circular(24.0),
    bottomLeft: Radius.circular(4.0),
  );
  static const BorderRadius lTopXsRight = BorderRadius.only(
    topLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(4.0),
  );
  static const BorderRadius lBottomXsBottom = BorderRadius.only(
    bottomLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(4.0),
  );
  static const BorderRadius lTopSLeft = BorderRadius.only(
    topLeft: Radius.circular(24.0),
    topRight: Radius.circular(8.0),
  );
  static const BorderRadius lRightSBottom = BorderRadius.only(
    topRight: Radius.circular(24.0),
    bottomLeft: Radius.circular(8.0),
  );
  static const BorderRadius lTopSRight = BorderRadius.only(
    topLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius lBottomSBottom = BorderRadius.only(
    bottomLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius lTopMLeft = BorderRadius.only(
    topLeft: Radius.circular(24.0),
    topRight: Radius.circular(16.0),
  );
  static const BorderRadius lRightMBottom = BorderRadius.only(
    topRight: Radius.circular(24.0),
    bottomLeft: Radius.circular(16.0),
  );
  static const BorderRadius lTopMRight = BorderRadius.only(
    topLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius lBottomMBottom = BorderRadius.only(
    bottomLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius lTopXlLeft = BorderRadius.only(
    topLeft: Radius.circular(24.0),
    topRight: Radius.circular(32.0),
  );
  static const BorderRadius lRightXlBottom = BorderRadius.only(
    topRight: Radius.circular(24.0),
    bottomLeft: Radius.circular(32.0),
  );
  static const BorderRadius lTopXlRight = BorderRadius.only(
    topLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(32.0),
  );
  static const BorderRadius lBottomXlBottom = BorderRadius.only(
    bottomLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(32.0),
  );
  static const BorderRadius lTopXxlLeft = BorderRadius.only(
    topLeft: Radius.circular(24.0),
    topRight: Radius.circular(48.0),
  );
  static const BorderRadius lRightXxlBottom = BorderRadius.only(
    topRight: Radius.circular(24.0),
    bottomLeft: Radius.circular(48.0),
  );
  static const BorderRadius lTopXxlRight = BorderRadius.only(
    topLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(48.0),
  );
  static const BorderRadius lBottomXxlBottom = BorderRadius.only(
    bottomLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(48.0),
  );
  static const BorderRadius xl = BorderRadius.all(Radius.circular(32.0));
  static const BorderRadius xlTop = BorderRadius.only(
    topLeft: Radius.circular(32.0),
    topRight: Radius.circular(32.0),
  );
  static const BorderRadius xlBottom = BorderRadius.only(
    bottomLeft: Radius.circular(32.0),
    bottomRight: Radius.circular(32.0),
  );
  static const BorderRadius xlLeft = BorderRadius.only(
    topLeft: Radius.circular(32.0),
    bottomLeft: Radius.circular(32.0),
  );
  static const BorderRadius xlRight = BorderRadius.only(
    topRight: Radius.circular(32.0),
    bottomRight: Radius.circular(32.0),
  );
  static const BorderRadius xlVertical = BorderRadius.vertical(
    top: Radius.circular(32.0),
    bottom: Radius.circular(32.0),
  );
  static const BorderRadius xlHorizontal = BorderRadius.horizontal(
    left: Radius.circular(32.0),
    right: Radius.circular(32.0),
  );
  static const BorderRadius xlTopLeft = BorderRadius.only(
    topLeft: Radius.circular(32.0),
  );
  static const BorderRadius xlTopRight = BorderRadius.only(
    topRight: Radius.circular(32.0),
  );
  static const BorderRadius xlBottomLeft = BorderRadius.only(
    bottomLeft: Radius.circular(32.0),
  );
  static const BorderRadius xlBottomRight = BorderRadius.only(
    bottomRight: Radius.circular(32.0),
  );
  static const BorderRadius xlTopLeftBottomRight = BorderRadius.only(
    topLeft: Radius.circular(32.0),
    bottomRight: Radius.circular(32.0),
  );
  static const BorderRadius xlTopRightBottomLeft = BorderRadius.only(
    topRight: Radius.circular(32.0),
    bottomLeft: Radius.circular(32.0),
  );
  static const BorderRadius xlTopZeroLeft = BorderRadius.only(
    topLeft: Radius.circular(32.0),
    topRight: Radius.circular(0.0),
  );
  static const BorderRadius xlRightZeroBottom = BorderRadius.only(
    topRight: Radius.circular(32.0),
    bottomLeft: Radius.circular(0.0),
  );
  static const BorderRadius xlTopZeroRight = BorderRadius.only(
    topLeft: Radius.circular(32.0),
    bottomRight: Radius.circular(0.0),
  );
  static const BorderRadius xlBottomZeroBottom = BorderRadius.only(
    bottomLeft: Radius.circular(32.0),
    bottomRight: Radius.circular(0.0),
  );
  static const BorderRadius xlTopXxsLeft = BorderRadius.only(
    topLeft: Radius.circular(32.0),
    topRight: Radius.circular(2.0),
  );
  static const BorderRadius xlRightXxsBottom = BorderRadius.only(
    topRight: Radius.circular(32.0),
    bottomLeft: Radius.circular(2.0),
  );
  static const BorderRadius xlTopXxsRight = BorderRadius.only(
    topLeft: Radius.circular(32.0),
    bottomRight: Radius.circular(2.0),
  );
  static const BorderRadius xlBottomXxsBottom = BorderRadius.only(
    bottomLeft: Radius.circular(32.0),
    bottomRight: Radius.circular(2.0),
  );
  static const BorderRadius xlTopXsLeft = BorderRadius.only(
    topLeft: Radius.circular(32.0),
    topRight: Radius.circular(4.0),
  );
  static const BorderRadius xlRightXsBottom = BorderRadius.only(
    topRight: Radius.circular(32.0),
    bottomLeft: Radius.circular(4.0),
  );
  static const BorderRadius xlTopXsRight = BorderRadius.only(
    topLeft: Radius.circular(32.0),
    bottomRight: Radius.circular(4.0),
  );
  static const BorderRadius xlBottomXsBottom = BorderRadius.only(
    bottomLeft: Radius.circular(32.0),
    bottomRight: Radius.circular(4.0),
  );
  static const BorderRadius xlTopSLeft = BorderRadius.only(
    topLeft: Radius.circular(32.0),
    topRight: Radius.circular(8.0),
  );
  static const BorderRadius xlRightSBottom = BorderRadius.only(
    topRight: Radius.circular(32.0),
    bottomLeft: Radius.circular(8.0),
  );
  static const BorderRadius xlTopSRight = BorderRadius.only(
    topLeft: Radius.circular(32.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius xlBottomSBottom = BorderRadius.only(
    bottomLeft: Radius.circular(32.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius xlTopMLeft = BorderRadius.only(
    topLeft: Radius.circular(32.0),
    topRight: Radius.circular(16.0),
  );
  static const BorderRadius xlRightMBottom = BorderRadius.only(
    topRight: Radius.circular(32.0),
    bottomLeft: Radius.circular(16.0),
  );
  static const BorderRadius xlTopMRight = BorderRadius.only(
    topLeft: Radius.circular(32.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius xlBottomMBottom = BorderRadius.only(
    bottomLeft: Radius.circular(32.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius xlTopLLeft = BorderRadius.only(
    topLeft: Radius.circular(32.0),
    topRight: Radius.circular(24.0),
  );
  static const BorderRadius xlRightLBottom = BorderRadius.only(
    topRight: Radius.circular(32.0),
    bottomLeft: Radius.circular(24.0),
  );
  static const BorderRadius xlTopLRight = BorderRadius.only(
    topLeft: Radius.circular(32.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius xlBottomLBottom = BorderRadius.only(
    bottomLeft: Radius.circular(32.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius xlTopXxlLeft = BorderRadius.only(
    topLeft: Radius.circular(32.0),
    topRight: Radius.circular(48.0),
  );
  static const BorderRadius xlRightXxlBottom = BorderRadius.only(
    topRight: Radius.circular(32.0),
    bottomLeft: Radius.circular(48.0),
  );
  static const BorderRadius xlTopXxlRight = BorderRadius.only(
    topLeft: Radius.circular(32.0),
    bottomRight: Radius.circular(48.0),
  );
  static const BorderRadius xlBottomXxlBottom = BorderRadius.only(
    bottomLeft: Radius.circular(32.0),
    bottomRight: Radius.circular(48.0),
  );
  static const BorderRadius xxl = BorderRadius.all(Radius.circular(48.0));
  static const BorderRadius xxlTop = BorderRadius.only(
    topLeft: Radius.circular(48.0),
    topRight: Radius.circular(48.0),
  );
  static const BorderRadius xxlBottom = BorderRadius.only(
    bottomLeft: Radius.circular(48.0),
    bottomRight: Radius.circular(48.0),
  );
  static const BorderRadius xxlLeft = BorderRadius.only(
    topLeft: Radius.circular(48.0),
    bottomLeft: Radius.circular(48.0),
  );
  static const BorderRadius xxlRight = BorderRadius.only(
    topRight: Radius.circular(48.0),
    bottomRight: Radius.circular(48.0),
  );
  static const BorderRadius xxlVertical = BorderRadius.vertical(
    top: Radius.circular(48.0),
    bottom: Radius.circular(48.0),
  );
  static const BorderRadius xxlHorizontal = BorderRadius.horizontal(
    left: Radius.circular(48.0),
    right: Radius.circular(48.0),
  );
  static const BorderRadius xxlTopLeft = BorderRadius.only(
    topLeft: Radius.circular(48.0),
  );
  static const BorderRadius xxlTopRight = BorderRadius.only(
    topRight: Radius.circular(48.0),
  );
  static const BorderRadius xxlBottomLeft = BorderRadius.only(
    bottomLeft: Radius.circular(48.0),
  );
  static const BorderRadius xxlBottomRight = BorderRadius.only(
    bottomRight: Radius.circular(48.0),
  );
  static const BorderRadius xxlTopLeftBottomRight = BorderRadius.only(
    topLeft: Radius.circular(48.0),
    bottomRight: Radius.circular(48.0),
  );
  static const BorderRadius xxlTopRightBottomLeft = BorderRadius.only(
    topRight: Radius.circular(48.0),
    bottomLeft: Radius.circular(48.0),
  );
  static const BorderRadius xxlTopZeroLeft = BorderRadius.only(
    topLeft: Radius.circular(48.0),
    topRight: Radius.circular(0.0),
  );
  static const BorderRadius xxlRightZeroBottom = BorderRadius.only(
    topRight: Radius.circular(48.0),
    bottomLeft: Radius.circular(0.0),
  );
  static const BorderRadius xxlTopZeroRight = BorderRadius.only(
    topLeft: Radius.circular(48.0),
    bottomRight: Radius.circular(0.0),
  );
  static const BorderRadius xxlBottomZeroBottom = BorderRadius.only(
    bottomLeft: Radius.circular(48.0),
    bottomRight: Radius.circular(0.0),
  );
  static const BorderRadius xxlTopXxsLeft = BorderRadius.only(
    topLeft: Radius.circular(48.0),
    topRight: Radius.circular(2.0),
  );
  static const BorderRadius xxlRightXxsBottom = BorderRadius.only(
    topRight: Radius.circular(48.0),
    bottomLeft: Radius.circular(2.0),
  );
  static const BorderRadius xxlTopXxsRight = BorderRadius.only(
    topLeft: Radius.circular(48.0),
    bottomRight: Radius.circular(2.0),
  );
  static const BorderRadius xxlBottomXxsBottom = BorderRadius.only(
    bottomLeft: Radius.circular(48.0),
    bottomRight: Radius.circular(2.0),
  );
  static const BorderRadius xxlTopXsLeft = BorderRadius.only(
    topLeft: Radius.circular(48.0),
    topRight: Radius.circular(4.0),
  );
  static const BorderRadius xxlRightXsBottom = BorderRadius.only(
    topRight: Radius.circular(48.0),
    bottomLeft: Radius.circular(4.0),
  );
  static const BorderRadius xxlTopXsRight = BorderRadius.only(
    topLeft: Radius.circular(48.0),
    bottomRight: Radius.circular(4.0),
  );
  static const BorderRadius xxlBottomXsBottom = BorderRadius.only(
    bottomLeft: Radius.circular(48.0),
    bottomRight: Radius.circular(4.0),
  );
  static const BorderRadius xxlTopSLeft = BorderRadius.only(
    topLeft: Radius.circular(48.0),
    topRight: Radius.circular(8.0),
  );
  static const BorderRadius xxlRightSBottom = BorderRadius.only(
    topRight: Radius.circular(48.0),
    bottomLeft: Radius.circular(8.0),
  );
  static const BorderRadius xxlTopSRight = BorderRadius.only(
    topLeft: Radius.circular(48.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius xxlBottomSBottom = BorderRadius.only(
    bottomLeft: Radius.circular(48.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius xxlTopMLeft = BorderRadius.only(
    topLeft: Radius.circular(48.0),
    topRight: Radius.circular(16.0),
  );
  static const BorderRadius xxlRightMBottom = BorderRadius.only(
    topRight: Radius.circular(48.0),
    bottomLeft: Radius.circular(16.0),
  );
  static const BorderRadius xxlTopMRight = BorderRadius.only(
    topLeft: Radius.circular(48.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius xxlBottomMBottom = BorderRadius.only(
    bottomLeft: Radius.circular(48.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius xxlTopLLeft = BorderRadius.only(
    topLeft: Radius.circular(48.0),
    topRight: Radius.circular(24.0),
  );
  static const BorderRadius xxlRightLBottom = BorderRadius.only(
    topRight: Radius.circular(48.0),
    bottomLeft: Radius.circular(24.0),
  );
  static const BorderRadius xxlTopLRight = BorderRadius.only(
    topLeft: Radius.circular(48.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius xxlBottomLBottom = BorderRadius.only(
    bottomLeft: Radius.circular(48.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius xxlTopXlLeft = BorderRadius.only(
    topLeft: Radius.circular(48.0),
    topRight: Radius.circular(32.0),
  );
  static const BorderRadius xxlRightXlBottom = BorderRadius.only(
    topRight: Radius.circular(48.0),
    bottomLeft: Radius.circular(32.0),
  );
  static const BorderRadius xxlTopXlRight = BorderRadius.only(
    topLeft: Radius.circular(48.0),
    bottomRight: Radius.circular(32.0),
  );
  static const BorderRadius xxlBottomXlBottom = BorderRadius.only(
    bottomLeft: Radius.circular(48.0),
    bottomRight: Radius.circular(32.0),
  );
}
