// dart format width=80
//
// GENERATED FILE — DO NOT MODIFY BY HAND
// --------------------------------------------------
// This file was generated by the `dimengen` package.
// Any changes to this file may be lost during rebuild.
//
// Generator: https://pub.dev/packages/dimengen
// Author: http://github.com/warioddly
// --------------------------------------------------
//

part of 'dimensions.dart';

// **************************************************************************
// InsetsGenerator
// **************************************************************************

abstract class InsetsDimensions {
  const InsetsDimensions._();

  static const EdgeInsets zero = EdgeInsets.all(0.0);
  static const EdgeInsets zeroTop = EdgeInsets.only(top: 0.0);
  static const EdgeInsets zeroBottom = EdgeInsets.only(bottom: 0.0);
  static const EdgeInsets zeroLeft = EdgeInsets.only(left: 0.0);
  static const EdgeInsets zeroRight = EdgeInsets.only(right: 0.0);
  static const EdgeInsets zeroVertical = EdgeInsets.symmetric(vertical: 0.0);
  static const EdgeInsets zeroHorizontal = EdgeInsets.symmetric(
    horizontal: 0.0,
  );
  static const EdgeInsets zeroTopXxsBottom = EdgeInsets.only(
    top: 0.0,
    bottom: 2.0,
  );
  static const EdgeInsets zeroLeftXxsRight = EdgeInsets.only(
    left: 0.0,
    right: 2.0,
  );
  static const EdgeInsets zeroTopXxsLeft = EdgeInsets.only(top: 0.0, left: 2.0);
  static const EdgeInsets zeroRightXxsBottom = EdgeInsets.only(
    right: 0.0,
    bottom: 2.0,
  );
  static const EdgeInsets zeroTopXsBottom = EdgeInsets.only(
    top: 0.0,
    bottom: 4.0,
  );
  static const EdgeInsets zeroLeftXsRight = EdgeInsets.only(
    left: 0.0,
    right: 4.0,
  );
  static const EdgeInsets zeroTopXsLeft = EdgeInsets.only(top: 0.0, left: 4.0);
  static const EdgeInsets zeroRightXsBottom = EdgeInsets.only(
    right: 0.0,
    bottom: 4.0,
  );
  static const EdgeInsets zeroTopSBottom = EdgeInsets.only(
    top: 0.0,
    bottom: 8.0,
  );
  static const EdgeInsets zeroLeftSRight = EdgeInsets.only(
    left: 0.0,
    right: 8.0,
  );
  static const EdgeInsets zeroTopSLeft = EdgeInsets.only(top: 0.0, left: 8.0);
  static const EdgeInsets zeroRightSBottom = EdgeInsets.only(
    right: 0.0,
    bottom: 8.0,
  );
  static const EdgeInsets zeroTopMBottom = EdgeInsets.only(
    top: 0.0,
    bottom: 16.0,
  );
  static const EdgeInsets zeroLeftMRight = EdgeInsets.only(
    left: 0.0,
    right: 16.0,
  );
  static const EdgeInsets zeroTopMLeft = EdgeInsets.only(top: 0.0, left: 16.0);
  static const EdgeInsets zeroRightMBottom = EdgeInsets.only(
    right: 0.0,
    bottom: 16.0,
  );
  static const EdgeInsets zeroTopLBottom = EdgeInsets.only(
    top: 0.0,
    bottom: 24.0,
  );
  static const EdgeInsets zeroLeftLRight = EdgeInsets.only(
    left: 0.0,
    right: 24.0,
  );
  static const EdgeInsets zeroTopLLeft = EdgeInsets.only(top: 0.0, left: 24.0);
  static const EdgeInsets zeroRightLBottom = EdgeInsets.only(
    right: 0.0,
    bottom: 24.0,
  );
  static const EdgeInsets zeroTopXlBottom = EdgeInsets.only(
    top: 0.0,
    bottom: 32.0,
  );
  static const EdgeInsets zeroLeftXlRight = EdgeInsets.only(
    left: 0.0,
    right: 32.0,
  );
  static const EdgeInsets zeroTopXlLeft = EdgeInsets.only(top: 0.0, left: 32.0);
  static const EdgeInsets zeroRightXlBottom = EdgeInsets.only(
    right: 0.0,
    bottom: 32.0,
  );
  static const EdgeInsets zeroTopXxlBottom = EdgeInsets.only(
    top: 0.0,
    bottom: 48.0,
  );
  static const EdgeInsets zeroLeftXxlRight = EdgeInsets.only(
    left: 0.0,
    right: 48.0,
  );
  static const EdgeInsets zeroTopXxlLeft = EdgeInsets.only(
    top: 0.0,
    left: 48.0,
  );
  static const EdgeInsets zeroRightXxlBottom = EdgeInsets.only(
    right: 0.0,
    bottom: 48.0,
  );
  static const EdgeInsets xxs = EdgeInsets.all(2.0);
  static const EdgeInsets xxsTop = EdgeInsets.only(top: 2.0);
  static const EdgeInsets xxsBottom = EdgeInsets.only(bottom: 2.0);
  static const EdgeInsets xxsLeft = EdgeInsets.only(left: 2.0);
  static const EdgeInsets xxsRight = EdgeInsets.only(right: 2.0);
  static const EdgeInsets xxsVertical = EdgeInsets.symmetric(vertical: 2.0);
  static const EdgeInsets xxsHorizontal = EdgeInsets.symmetric(horizontal: 2.0);
  static const EdgeInsets xxsTopZeroBottom = EdgeInsets.only(
    top: 2.0,
    bottom: 0.0,
  );
  static const EdgeInsets xxsLeftZeroRight = EdgeInsets.only(
    left: 2.0,
    right: 0.0,
  );
  static const EdgeInsets xxsTopZeroLeft = EdgeInsets.only(top: 2.0, left: 0.0);
  static const EdgeInsets xxsRightZeroBottom = EdgeInsets.only(
    right: 2.0,
    bottom: 0.0,
  );
  static const EdgeInsets xxsTopXsBottom = EdgeInsets.only(
    top: 2.0,
    bottom: 4.0,
  );
  static const EdgeInsets xxsLeftXsRight = EdgeInsets.only(
    left: 2.0,
    right: 4.0,
  );
  static const EdgeInsets xxsTopXsLeft = EdgeInsets.only(top: 2.0, left: 4.0);
  static const EdgeInsets xxsRightXsBottom = EdgeInsets.only(
    right: 2.0,
    bottom: 4.0,
  );
  static const EdgeInsets xxsTopSBottom = EdgeInsets.only(
    top: 2.0,
    bottom: 8.0,
  );
  static const EdgeInsets xxsLeftSRight = EdgeInsets.only(
    left: 2.0,
    right: 8.0,
  );
  static const EdgeInsets xxsTopSLeft = EdgeInsets.only(top: 2.0, left: 8.0);
  static const EdgeInsets xxsRightSBottom = EdgeInsets.only(
    right: 2.0,
    bottom: 8.0,
  );
  static const EdgeInsets xxsTopMBottom = EdgeInsets.only(
    top: 2.0,
    bottom: 16.0,
  );
  static const EdgeInsets xxsLeftMRight = EdgeInsets.only(
    left: 2.0,
    right: 16.0,
  );
  static const EdgeInsets xxsTopMLeft = EdgeInsets.only(top: 2.0, left: 16.0);
  static const EdgeInsets xxsRightMBottom = EdgeInsets.only(
    right: 2.0,
    bottom: 16.0,
  );
  static const EdgeInsets xxsTopLBottom = EdgeInsets.only(
    top: 2.0,
    bottom: 24.0,
  );
  static const EdgeInsets xxsLeftLRight = EdgeInsets.only(
    left: 2.0,
    right: 24.0,
  );
  static const EdgeInsets xxsTopLLeft = EdgeInsets.only(top: 2.0, left: 24.0);
  static const EdgeInsets xxsRightLBottom = EdgeInsets.only(
    right: 2.0,
    bottom: 24.0,
  );
  static const EdgeInsets xxsTopXlBottom = EdgeInsets.only(
    top: 2.0,
    bottom: 32.0,
  );
  static const EdgeInsets xxsLeftXlRight = EdgeInsets.only(
    left: 2.0,
    right: 32.0,
  );
  static const EdgeInsets xxsTopXlLeft = EdgeInsets.only(top: 2.0, left: 32.0);
  static const EdgeInsets xxsRightXlBottom = EdgeInsets.only(
    right: 2.0,
    bottom: 32.0,
  );
  static const EdgeInsets xxsTopXxlBottom = EdgeInsets.only(
    top: 2.0,
    bottom: 48.0,
  );
  static const EdgeInsets xxsLeftXxlRight = EdgeInsets.only(
    left: 2.0,
    right: 48.0,
  );
  static const EdgeInsets xxsTopXxlLeft = EdgeInsets.only(top: 2.0, left: 48.0);
  static const EdgeInsets xxsRightXxlBottom = EdgeInsets.only(
    right: 2.0,
    bottom: 48.0,
  );
  static const EdgeInsets xs = EdgeInsets.all(4.0);
  static const EdgeInsets xsTop = EdgeInsets.only(top: 4.0);
  static const EdgeInsets xsBottom = EdgeInsets.only(bottom: 4.0);
  static const EdgeInsets xsLeft = EdgeInsets.only(left: 4.0);
  static const EdgeInsets xsRight = EdgeInsets.only(right: 4.0);
  static const EdgeInsets xsVertical = EdgeInsets.symmetric(vertical: 4.0);
  static const EdgeInsets xsHorizontal = EdgeInsets.symmetric(horizontal: 4.0);
  static const EdgeInsets xsTopZeroBottom = EdgeInsets.only(
    top: 4.0,
    bottom: 0.0,
  );
  static const EdgeInsets xsLeftZeroRight = EdgeInsets.only(
    left: 4.0,
    right: 0.0,
  );
  static const EdgeInsets xsTopZeroLeft = EdgeInsets.only(top: 4.0, left: 0.0);
  static const EdgeInsets xsRightZeroBottom = EdgeInsets.only(
    right: 4.0,
    bottom: 0.0,
  );
  static const EdgeInsets xsTopXxsBottom = EdgeInsets.only(
    top: 4.0,
    bottom: 2.0,
  );
  static const EdgeInsets xsLeftXxsRight = EdgeInsets.only(
    left: 4.0,
    right: 2.0,
  );
  static const EdgeInsets xsTopXxsLeft = EdgeInsets.only(top: 4.0, left: 2.0);
  static const EdgeInsets xsRightXxsBottom = EdgeInsets.only(
    right: 4.0,
    bottom: 2.0,
  );
  static const EdgeInsets xsTopSBottom = EdgeInsets.only(top: 4.0, bottom: 8.0);
  static const EdgeInsets xsLeftSRight = EdgeInsets.only(left: 4.0, right: 8.0);
  static const EdgeInsets xsTopSLeft = EdgeInsets.only(top: 4.0, left: 8.0);
  static const EdgeInsets xsRightSBottom = EdgeInsets.only(
    right: 4.0,
    bottom: 8.0,
  );
  static const EdgeInsets xsTopMBottom = EdgeInsets.only(
    top: 4.0,
    bottom: 16.0,
  );
  static const EdgeInsets xsLeftMRight = EdgeInsets.only(
    left: 4.0,
    right: 16.0,
  );
  static const EdgeInsets xsTopMLeft = EdgeInsets.only(top: 4.0, left: 16.0);
  static const EdgeInsets xsRightMBottom = EdgeInsets.only(
    right: 4.0,
    bottom: 16.0,
  );
  static const EdgeInsets xsTopLBottom = EdgeInsets.only(
    top: 4.0,
    bottom: 24.0,
  );
  static const EdgeInsets xsLeftLRight = EdgeInsets.only(
    left: 4.0,
    right: 24.0,
  );
  static const EdgeInsets xsTopLLeft = EdgeInsets.only(top: 4.0, left: 24.0);
  static const EdgeInsets xsRightLBottom = EdgeInsets.only(
    right: 4.0,
    bottom: 24.0,
  );
  static const EdgeInsets xsTopXlBottom = EdgeInsets.only(
    top: 4.0,
    bottom: 32.0,
  );
  static const EdgeInsets xsLeftXlRight = EdgeInsets.only(
    left: 4.0,
    right: 32.0,
  );
  static const EdgeInsets xsTopXlLeft = EdgeInsets.only(top: 4.0, left: 32.0);
  static const EdgeInsets xsRightXlBottom = EdgeInsets.only(
    right: 4.0,
    bottom: 32.0,
  );
  static const EdgeInsets xsTopXxlBottom = EdgeInsets.only(
    top: 4.0,
    bottom: 48.0,
  );
  static const EdgeInsets xsLeftXxlRight = EdgeInsets.only(
    left: 4.0,
    right: 48.0,
  );
  static const EdgeInsets xsTopXxlLeft = EdgeInsets.only(top: 4.0, left: 48.0);
  static const EdgeInsets xsRightXxlBottom = EdgeInsets.only(
    right: 4.0,
    bottom: 48.0,
  );
  static const EdgeInsets s = EdgeInsets.all(8.0);
  static const EdgeInsets sTop = EdgeInsets.only(top: 8.0);
  static const EdgeInsets sBottom = EdgeInsets.only(bottom: 8.0);
  static const EdgeInsets sLeft = EdgeInsets.only(left: 8.0);
  static const EdgeInsets sRight = EdgeInsets.only(right: 8.0);
  static const EdgeInsets sVertical = EdgeInsets.symmetric(vertical: 8.0);
  static const EdgeInsets sHorizontal = EdgeInsets.symmetric(horizontal: 8.0);
  static const EdgeInsets sTopZeroBottom = EdgeInsets.only(
    top: 8.0,
    bottom: 0.0,
  );
  static const EdgeInsets sLeftZeroRight = EdgeInsets.only(
    left: 8.0,
    right: 0.0,
  );
  static const EdgeInsets sTopZeroLeft = EdgeInsets.only(top: 8.0, left: 0.0);
  static const EdgeInsets sRightZeroBottom = EdgeInsets.only(
    right: 8.0,
    bottom: 0.0,
  );
  static const EdgeInsets sTopXxsBottom = EdgeInsets.only(
    top: 8.0,
    bottom: 2.0,
  );
  static const EdgeInsets sLeftXxsRight = EdgeInsets.only(
    left: 8.0,
    right: 2.0,
  );
  static const EdgeInsets sTopXxsLeft = EdgeInsets.only(top: 8.0, left: 2.0);
  static const EdgeInsets sRightXxsBottom = EdgeInsets.only(
    right: 8.0,
    bottom: 2.0,
  );
  static const EdgeInsets sTopXsBottom = EdgeInsets.only(top: 8.0, bottom: 4.0);
  static const EdgeInsets sLeftXsRight = EdgeInsets.only(left: 8.0, right: 4.0);
  static const EdgeInsets sTopXsLeft = EdgeInsets.only(top: 8.0, left: 4.0);
  static const EdgeInsets sRightXsBottom = EdgeInsets.only(
    right: 8.0,
    bottom: 4.0,
  );
  static const EdgeInsets sTopMBottom = EdgeInsets.only(top: 8.0, bottom: 16.0);
  static const EdgeInsets sLeftMRight = EdgeInsets.only(left: 8.0, right: 16.0);
  static const EdgeInsets sTopMLeft = EdgeInsets.only(top: 8.0, left: 16.0);
  static const EdgeInsets sRightMBottom = EdgeInsets.only(
    right: 8.0,
    bottom: 16.0,
  );
  static const EdgeInsets sTopLBottom = EdgeInsets.only(top: 8.0, bottom: 24.0);
  static const EdgeInsets sLeftLRight = EdgeInsets.only(left: 8.0, right: 24.0);
  static const EdgeInsets sTopLLeft = EdgeInsets.only(top: 8.0, left: 24.0);
  static const EdgeInsets sRightLBottom = EdgeInsets.only(
    right: 8.0,
    bottom: 24.0,
  );
  static const EdgeInsets sTopXlBottom = EdgeInsets.only(
    top: 8.0,
    bottom: 32.0,
  );
  static const EdgeInsets sLeftXlRight = EdgeInsets.only(
    left: 8.0,
    right: 32.0,
  );
  static const EdgeInsets sTopXlLeft = EdgeInsets.only(top: 8.0, left: 32.0);
  static const EdgeInsets sRightXlBottom = EdgeInsets.only(
    right: 8.0,
    bottom: 32.0,
  );
  static const EdgeInsets sTopXxlBottom = EdgeInsets.only(
    top: 8.0,
    bottom: 48.0,
  );
  static const EdgeInsets sLeftXxlRight = EdgeInsets.only(
    left: 8.0,
    right: 48.0,
  );
  static const EdgeInsets sTopXxlLeft = EdgeInsets.only(top: 8.0, left: 48.0);
  static const EdgeInsets sRightXxlBottom = EdgeInsets.only(
    right: 8.0,
    bottom: 48.0,
  );
  static const EdgeInsets m = EdgeInsets.all(16.0);
  static const EdgeInsets mTop = EdgeInsets.only(top: 16.0);
  static const EdgeInsets mBottom = EdgeInsets.only(bottom: 16.0);
  static const EdgeInsets mLeft = EdgeInsets.only(left: 16.0);
  static const EdgeInsets mRight = EdgeInsets.only(right: 16.0);
  static const EdgeInsets mVertical = EdgeInsets.symmetric(vertical: 16.0);
  static const EdgeInsets mHorizontal = EdgeInsets.symmetric(horizontal: 16.0);
  static const EdgeInsets mTopZeroBottom = EdgeInsets.only(
    top: 16.0,
    bottom: 0.0,
  );
  static const EdgeInsets mLeftZeroRight = EdgeInsets.only(
    left: 16.0,
    right: 0.0,
  );
  static const EdgeInsets mTopZeroLeft = EdgeInsets.only(top: 16.0, left: 0.0);
  static const EdgeInsets mRightZeroBottom = EdgeInsets.only(
    right: 16.0,
    bottom: 0.0,
  );
  static const EdgeInsets mTopXxsBottom = EdgeInsets.only(
    top: 16.0,
    bottom: 2.0,
  );
  static const EdgeInsets mLeftXxsRight = EdgeInsets.only(
    left: 16.0,
    right: 2.0,
  );
  static const EdgeInsets mTopXxsLeft = EdgeInsets.only(top: 16.0, left: 2.0);
  static const EdgeInsets mRightXxsBottom = EdgeInsets.only(
    right: 16.0,
    bottom: 2.0,
  );
  static const EdgeInsets mTopXsBottom = EdgeInsets.only(
    top: 16.0,
    bottom: 4.0,
  );
  static const EdgeInsets mLeftXsRight = EdgeInsets.only(
    left: 16.0,
    right: 4.0,
  );
  static const EdgeInsets mTopXsLeft = EdgeInsets.only(top: 16.0, left: 4.0);
  static const EdgeInsets mRightXsBottom = EdgeInsets.only(
    right: 16.0,
    bottom: 4.0,
  );
  static const EdgeInsets mTopSBottom = EdgeInsets.only(top: 16.0, bottom: 8.0);
  static const EdgeInsets mLeftSRight = EdgeInsets.only(left: 16.0, right: 8.0);
  static const EdgeInsets mTopSLeft = EdgeInsets.only(top: 16.0, left: 8.0);
  static const EdgeInsets mRightSBottom = EdgeInsets.only(
    right: 16.0,
    bottom: 8.0,
  );
  static const EdgeInsets mTopLBottom = EdgeInsets.only(
    top: 16.0,
    bottom: 24.0,
  );
  static const EdgeInsets mLeftLRight = EdgeInsets.only(
    left: 16.0,
    right: 24.0,
  );
  static const EdgeInsets mTopLLeft = EdgeInsets.only(top: 16.0, left: 24.0);
  static const EdgeInsets mRightLBottom = EdgeInsets.only(
    right: 16.0,
    bottom: 24.0,
  );
  static const EdgeInsets mTopXlBottom = EdgeInsets.only(
    top: 16.0,
    bottom: 32.0,
  );
  static const EdgeInsets mLeftXlRight = EdgeInsets.only(
    left: 16.0,
    right: 32.0,
  );
  static const EdgeInsets mTopXlLeft = EdgeInsets.only(top: 16.0, left: 32.0);
  static const EdgeInsets mRightXlBottom = EdgeInsets.only(
    right: 16.0,
    bottom: 32.0,
  );
  static const EdgeInsets mTopXxlBottom = EdgeInsets.only(
    top: 16.0,
    bottom: 48.0,
  );
  static const EdgeInsets mLeftXxlRight = EdgeInsets.only(
    left: 16.0,
    right: 48.0,
  );
  static const EdgeInsets mTopXxlLeft = EdgeInsets.only(top: 16.0, left: 48.0);
  static const EdgeInsets mRightXxlBottom = EdgeInsets.only(
    right: 16.0,
    bottom: 48.0,
  );
  static const EdgeInsets l = EdgeInsets.all(24.0);
  static const EdgeInsets lTop = EdgeInsets.only(top: 24.0);
  static const EdgeInsets lBottom = EdgeInsets.only(bottom: 24.0);
  static const EdgeInsets lLeft = EdgeInsets.only(left: 24.0);
  static const EdgeInsets lRight = EdgeInsets.only(right: 24.0);
  static const EdgeInsets lVertical = EdgeInsets.symmetric(vertical: 24.0);
  static const EdgeInsets lHorizontal = EdgeInsets.symmetric(horizontal: 24.0);
  static const EdgeInsets lTopZeroBottom = EdgeInsets.only(
    top: 24.0,
    bottom: 0.0,
  );
  static const EdgeInsets lLeftZeroRight = EdgeInsets.only(
    left: 24.0,
    right: 0.0,
  );
  static const EdgeInsets lTopZeroLeft = EdgeInsets.only(top: 24.0, left: 0.0);
  static const EdgeInsets lRightZeroBottom = EdgeInsets.only(
    right: 24.0,
    bottom: 0.0,
  );
  static const EdgeInsets lTopXxsBottom = EdgeInsets.only(
    top: 24.0,
    bottom: 2.0,
  );
  static const EdgeInsets lLeftXxsRight = EdgeInsets.only(
    left: 24.0,
    right: 2.0,
  );
  static const EdgeInsets lTopXxsLeft = EdgeInsets.only(top: 24.0, left: 2.0);
  static const EdgeInsets lRightXxsBottom = EdgeInsets.only(
    right: 24.0,
    bottom: 2.0,
  );
  static const EdgeInsets lTopXsBottom = EdgeInsets.only(
    top: 24.0,
    bottom: 4.0,
  );
  static const EdgeInsets lLeftXsRight = EdgeInsets.only(
    left: 24.0,
    right: 4.0,
  );
  static const EdgeInsets lTopXsLeft = EdgeInsets.only(top: 24.0, left: 4.0);
  static const EdgeInsets lRightXsBottom = EdgeInsets.only(
    right: 24.0,
    bottom: 4.0,
  );
  static const EdgeInsets lTopSBottom = EdgeInsets.only(top: 24.0, bottom: 8.0);
  static const EdgeInsets lLeftSRight = EdgeInsets.only(left: 24.0, right: 8.0);
  static const EdgeInsets lTopSLeft = EdgeInsets.only(top: 24.0, left: 8.0);
  static const EdgeInsets lRightSBottom = EdgeInsets.only(
    right: 24.0,
    bottom: 8.0,
  );
  static const EdgeInsets lTopMBottom = EdgeInsets.only(
    top: 24.0,
    bottom: 16.0,
  );
  static const EdgeInsets lLeftMRight = EdgeInsets.only(
    left: 24.0,
    right: 16.0,
  );
  static const EdgeInsets lTopMLeft = EdgeInsets.only(top: 24.0, left: 16.0);
  static const EdgeInsets lRightMBottom = EdgeInsets.only(
    right: 24.0,
    bottom: 16.0,
  );
  static const EdgeInsets lTopXlBottom = EdgeInsets.only(
    top: 24.0,
    bottom: 32.0,
  );
  static const EdgeInsets lLeftXlRight = EdgeInsets.only(
    left: 24.0,
    right: 32.0,
  );
  static const EdgeInsets lTopXlLeft = EdgeInsets.only(top: 24.0, left: 32.0);
  static const EdgeInsets lRightXlBottom = EdgeInsets.only(
    right: 24.0,
    bottom: 32.0,
  );
  static const EdgeInsets lTopXxlBottom = EdgeInsets.only(
    top: 24.0,
    bottom: 48.0,
  );
  static const EdgeInsets lLeftXxlRight = EdgeInsets.only(
    left: 24.0,
    right: 48.0,
  );
  static const EdgeInsets lTopXxlLeft = EdgeInsets.only(top: 24.0, left: 48.0);
  static const EdgeInsets lRightXxlBottom = EdgeInsets.only(
    right: 24.0,
    bottom: 48.0,
  );
  static const EdgeInsets xl = EdgeInsets.all(32.0);
  static const EdgeInsets xlTop = EdgeInsets.only(top: 32.0);
  static const EdgeInsets xlBottom = EdgeInsets.only(bottom: 32.0);
  static const EdgeInsets xlLeft = EdgeInsets.only(left: 32.0);
  static const EdgeInsets xlRight = EdgeInsets.only(right: 32.0);
  static const EdgeInsets xlVertical = EdgeInsets.symmetric(vertical: 32.0);
  static const EdgeInsets xlHorizontal = EdgeInsets.symmetric(horizontal: 32.0);
  static const EdgeInsets xlTopZeroBottom = EdgeInsets.only(
    top: 32.0,
    bottom: 0.0,
  );
  static const EdgeInsets xlLeftZeroRight = EdgeInsets.only(
    left: 32.0,
    right: 0.0,
  );
  static const EdgeInsets xlTopZeroLeft = EdgeInsets.only(top: 32.0, left: 0.0);
  static const EdgeInsets xlRightZeroBottom = EdgeInsets.only(
    right: 32.0,
    bottom: 0.0,
  );
  static const EdgeInsets xlTopXxsBottom = EdgeInsets.only(
    top: 32.0,
    bottom: 2.0,
  );
  static const EdgeInsets xlLeftXxsRight = EdgeInsets.only(
    left: 32.0,
    right: 2.0,
  );
  static const EdgeInsets xlTopXxsLeft = EdgeInsets.only(top: 32.0, left: 2.0);
  static const EdgeInsets xlRightXxsBottom = EdgeInsets.only(
    right: 32.0,
    bottom: 2.0,
  );
  static const EdgeInsets xlTopXsBottom = EdgeInsets.only(
    top: 32.0,
    bottom: 4.0,
  );
  static const EdgeInsets xlLeftXsRight = EdgeInsets.only(
    left: 32.0,
    right: 4.0,
  );
  static const EdgeInsets xlTopXsLeft = EdgeInsets.only(top: 32.0, left: 4.0);
  static const EdgeInsets xlRightXsBottom = EdgeInsets.only(
    right: 32.0,
    bottom: 4.0,
  );
  static const EdgeInsets xlTopSBottom = EdgeInsets.only(
    top: 32.0,
    bottom: 8.0,
  );
  static const EdgeInsets xlLeftSRight = EdgeInsets.only(
    left: 32.0,
    right: 8.0,
  );
  static const EdgeInsets xlTopSLeft = EdgeInsets.only(top: 32.0, left: 8.0);
  static const EdgeInsets xlRightSBottom = EdgeInsets.only(
    right: 32.0,
    bottom: 8.0,
  );
  static const EdgeInsets xlTopMBottom = EdgeInsets.only(
    top: 32.0,
    bottom: 16.0,
  );
  static const EdgeInsets xlLeftMRight = EdgeInsets.only(
    left: 32.0,
    right: 16.0,
  );
  static const EdgeInsets xlTopMLeft = EdgeInsets.only(top: 32.0, left: 16.0);
  static const EdgeInsets xlRightMBottom = EdgeInsets.only(
    right: 32.0,
    bottom: 16.0,
  );
  static const EdgeInsets xlTopLBottom = EdgeInsets.only(
    top: 32.0,
    bottom: 24.0,
  );
  static const EdgeInsets xlLeftLRight = EdgeInsets.only(
    left: 32.0,
    right: 24.0,
  );
  static const EdgeInsets xlTopLLeft = EdgeInsets.only(top: 32.0, left: 24.0);
  static const EdgeInsets xlRightLBottom = EdgeInsets.only(
    right: 32.0,
    bottom: 24.0,
  );
  static const EdgeInsets xlTopXxlBottom = EdgeInsets.only(
    top: 32.0,
    bottom: 48.0,
  );
  static const EdgeInsets xlLeftXxlRight = EdgeInsets.only(
    left: 32.0,
    right: 48.0,
  );
  static const EdgeInsets xlTopXxlLeft = EdgeInsets.only(top: 32.0, left: 48.0);
  static const EdgeInsets xlRightXxlBottom = EdgeInsets.only(
    right: 32.0,
    bottom: 48.0,
  );
  static const EdgeInsets xxl = EdgeInsets.all(48.0);
  static const EdgeInsets xxlTop = EdgeInsets.only(top: 48.0);
  static const EdgeInsets xxlBottom = EdgeInsets.only(bottom: 48.0);
  static const EdgeInsets xxlLeft = EdgeInsets.only(left: 48.0);
  static const EdgeInsets xxlRight = EdgeInsets.only(right: 48.0);
  static const EdgeInsets xxlVertical = EdgeInsets.symmetric(vertical: 48.0);
  static const EdgeInsets xxlHorizontal = EdgeInsets.symmetric(
    horizontal: 48.0,
  );
  static const EdgeInsets xxlTopZeroBottom = EdgeInsets.only(
    top: 48.0,
    bottom: 0.0,
  );
  static const EdgeInsets xxlLeftZeroRight = EdgeInsets.only(
    left: 48.0,
    right: 0.0,
  );
  static const EdgeInsets xxlTopZeroLeft = EdgeInsets.only(
    top: 48.0,
    left: 0.0,
  );
  static const EdgeInsets xxlRightZeroBottom = EdgeInsets.only(
    right: 48.0,
    bottom: 0.0,
  );
  static const EdgeInsets xxlTopXxsBottom = EdgeInsets.only(
    top: 48.0,
    bottom: 2.0,
  );
  static const EdgeInsets xxlLeftXxsRight = EdgeInsets.only(
    left: 48.0,
    right: 2.0,
  );
  static const EdgeInsets xxlTopXxsLeft = EdgeInsets.only(top: 48.0, left: 2.0);
  static const EdgeInsets xxlRightXxsBottom = EdgeInsets.only(
    right: 48.0,
    bottom: 2.0,
  );
  static const EdgeInsets xxlTopXsBottom = EdgeInsets.only(
    top: 48.0,
    bottom: 4.0,
  );
  static const EdgeInsets xxlLeftXsRight = EdgeInsets.only(
    left: 48.0,
    right: 4.0,
  );
  static const EdgeInsets xxlTopXsLeft = EdgeInsets.only(top: 48.0, left: 4.0);
  static const EdgeInsets xxlRightXsBottom = EdgeInsets.only(
    right: 48.0,
    bottom: 4.0,
  );
  static const EdgeInsets xxlTopSBottom = EdgeInsets.only(
    top: 48.0,
    bottom: 8.0,
  );
  static const EdgeInsets xxlLeftSRight = EdgeInsets.only(
    left: 48.0,
    right: 8.0,
  );
  static const EdgeInsets xxlTopSLeft = EdgeInsets.only(top: 48.0, left: 8.0);
  static const EdgeInsets xxlRightSBottom = EdgeInsets.only(
    right: 48.0,
    bottom: 8.0,
  );
  static const EdgeInsets xxlTopMBottom = EdgeInsets.only(
    top: 48.0,
    bottom: 16.0,
  );
  static const EdgeInsets xxlLeftMRight = EdgeInsets.only(
    left: 48.0,
    right: 16.0,
  );
  static const EdgeInsets xxlTopMLeft = EdgeInsets.only(top: 48.0, left: 16.0);
  static const EdgeInsets xxlRightMBottom = EdgeInsets.only(
    right: 48.0,
    bottom: 16.0,
  );
  static const EdgeInsets xxlTopLBottom = EdgeInsets.only(
    top: 48.0,
    bottom: 24.0,
  );
  static const EdgeInsets xxlLeftLRight = EdgeInsets.only(
    left: 48.0,
    right: 24.0,
  );
  static const EdgeInsets xxlTopLLeft = EdgeInsets.only(top: 48.0, left: 24.0);
  static const EdgeInsets xxlRightLBottom = EdgeInsets.only(
    right: 48.0,
    bottom: 24.0,
  );
  static const EdgeInsets xxlTopXlBottom = EdgeInsets.only(
    top: 48.0,
    bottom: 32.0,
  );
  static const EdgeInsets xxlLeftXlRight = EdgeInsets.only(
    left: 48.0,
    right: 32.0,
  );
  static const EdgeInsets xxlTopXlLeft = EdgeInsets.only(top: 48.0, left: 32.0);
  static const EdgeInsets xxlRightXlBottom = EdgeInsets.only(
    right: 48.0,
    bottom: 32.0,
  );
}

// **************************************************************************
// SpacesGenerator
// **************************************************************************

abstract class SpacesDimensions {
  const SpacesDimensions._();

  static const SizedBox zero = SizedBox.square(dimension: 0.0);
  static const SizedBox zeroVertical = SizedBox(height: 0.0);
  static const SizedBox zeroHorizontal = SizedBox(width: 0.0);
  static const SizedBox xxs = SizedBox.square(dimension: 2.0);
  static const SizedBox xxsVertical = SizedBox(height: 2.0);
  static const SizedBox xxsHorizontal = SizedBox(width: 2.0);
  static const SizedBox xs = SizedBox.square(dimension: 4.0);
  static const SizedBox xsVertical = SizedBox(height: 4.0);
  static const SizedBox xsHorizontal = SizedBox(width: 4.0);
  static const SizedBox s = SizedBox.square(dimension: 8.0);
  static const SizedBox sVertical = SizedBox(height: 8.0);
  static const SizedBox sHorizontal = SizedBox(width: 8.0);
  static const SizedBox m = SizedBox.square(dimension: 16.0);
  static const SizedBox mVertical = SizedBox(height: 16.0);
  static const SizedBox mHorizontal = SizedBox(width: 16.0);
  static const SizedBox l = SizedBox.square(dimension: 24.0);
  static const SizedBox lVertical = SizedBox(height: 24.0);
  static const SizedBox lHorizontal = SizedBox(width: 24.0);
  static const SizedBox xl = SizedBox.square(dimension: 32.0);
  static const SizedBox xlVertical = SizedBox(height: 32.0);
  static const SizedBox xlHorizontal = SizedBox(width: 32.0);
  static const SizedBox xxl = SizedBox.square(dimension: 48.0);
  static const SizedBox xxlVertical = SizedBox(height: 48.0);
  static const SizedBox xxlHorizontal = SizedBox(width: 48.0);
  static SizedBox h(double value) => SizedBox(height: value);
  static SizedBox w(double value) => SizedBox(width: value);
}
