// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'dimensions.dart';

// **************************************************************************
// DimensionsGenerator
// **************************************************************************

// --------------------------------------------------
// This file was generated by the `dimengen` package.
// Any changes to this file may be lost during rebuild.
//
// Generator: https://pub.dev/packages/dimengen
// Author: http://github.com/warioddly
// --------------------------------------------------

abstract class Insets {
  const Insets._();

  static const EdgeInsets s = .all(8.0);
  static const EdgeInsets sTop = .only(top: 8.0);
  static const EdgeInsets sBottom = .only(bottom: 8.0);
  static const EdgeInsets sLeft = .only(left: 8.0);
  static const EdgeInsets sRight = .only(right: 8.0);
  static const EdgeInsets sVertical = .symmetric(vertical: 8.0);
  static const EdgeInsets sHorizontal = .symmetric(horizontal: 8.0);
  static const EdgeInsets sTopMBottom = .only(top: 8.0, bottom: 16.0);
  static const EdgeInsets sLeftMRight = .only(left: 8.0, right: 16.0);
  static const EdgeInsets sTopMLeft = .only(top: 8.0, left: 16.0);
  static const EdgeInsets sRightMBottom = .only(right: 8.0, bottom: 16.0);
  static const EdgeInsets sTopLBottom = .only(top: 8.0, bottom: 24.0);
  static const EdgeInsets sLeftLRight = .only(left: 8.0, right: 24.0);
  static const EdgeInsets sTopLLeft = .only(top: 8.0, left: 24.0);
  static const EdgeInsets sRightLBottom = .only(right: 8.0, bottom: 24.0);
  static const EdgeInsets m = .all(16.0);
  static const EdgeInsets mTop = .only(top: 16.0);
  static const EdgeInsets mBottom = .only(bottom: 16.0);
  static const EdgeInsets mLeft = .only(left: 16.0);
  static const EdgeInsets mRight = .only(right: 16.0);
  static const EdgeInsets mVertical = .symmetric(vertical: 16.0);
  static const EdgeInsets mHorizontal = .symmetric(horizontal: 16.0);
  static const EdgeInsets mTopSBottom = .only(top: 16.0, bottom: 8.0);
  static const EdgeInsets mLeftSRight = .only(left: 16.0, right: 8.0);
  static const EdgeInsets mTopSLeft = .only(top: 16.0, left: 8.0);
  static const EdgeInsets mRightSBottom = .only(right: 16.0, bottom: 8.0);
  static const EdgeInsets mTopLBottom = .only(top: 16.0, bottom: 24.0);
  static const EdgeInsets mLeftLRight = .only(left: 16.0, right: 24.0);
  static const EdgeInsets mTopLLeft = .only(top: 16.0, left: 24.0);
  static const EdgeInsets mRightLBottom = .only(right: 16.0, bottom: 24.0);
  static const EdgeInsets l = .all(24.0);
  static const EdgeInsets lTop = .only(top: 24.0);
  static const EdgeInsets lBottom = .only(bottom: 24.0);
  static const EdgeInsets lLeft = .only(left: 24.0);
  static const EdgeInsets lRight = .only(right: 24.0);
  static const EdgeInsets lVertical = .symmetric(vertical: 24.0);
  static const EdgeInsets lHorizontal = .symmetric(horizontal: 24.0);
  static const EdgeInsets lTopSBottom = .only(top: 24.0, bottom: 8.0);
  static const EdgeInsets lLeftSRight = .only(left: 24.0, right: 8.0);
  static const EdgeInsets lTopSLeft = .only(top: 24.0, left: 8.0);
  static const EdgeInsets lRightSBottom = .only(right: 24.0, bottom: 8.0);
  static const EdgeInsets lTopMBottom = .only(top: 24.0, bottom: 16.0);
  static const EdgeInsets lLeftMRight = .only(left: 24.0, right: 16.0);
  static const EdgeInsets lTopMLeft = .only(top: 24.0, left: 16.0);
  static const EdgeInsets lRightMBottom = .only(right: 24.0, bottom: 16.0);
}

abstract class DesignSpaces {
  const DesignSpaces._();

  static const SizedBox s = .square(dimension: 8.0);
  static const SizedBox sVertical = SizedBox(height: 8.0);
  static const SizedBox sHorizontal = SizedBox(width: 8.0);
  static const SizedBox m = .square(dimension: 16.0);
  static const SizedBox mVertical = SizedBox(height: 16.0);
  static const SizedBox mHorizontal = SizedBox(width: 16.0);
  static const SizedBox l = .square(dimension: 24.0);
  static const SizedBox lVertical = SizedBox(height: 24.0);
  static const SizedBox lHorizontal = SizedBox(width: 24.0);
  static SizedBox h(double value) => SizedBox(height: value);
  static SizedBox w(double value) => SizedBox(width: value);
  static SizedBox square(double value) => .square(dimension: value);
}

abstract class Borders {
  const Borders._();

  static const BorderRadius s = .all(Radius.circular(8.0));
  static const BorderRadius sTop = .only(
    topLeft: Radius.circular(8.0),
    topRight: Radius.circular(8.0),
  );
  static const BorderRadius sBottom = .only(
    bottomLeft: Radius.circular(8.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius sLeft = .only(
    topLeft: Radius.circular(8.0),
    bottomLeft: Radius.circular(8.0),
  );
  static const BorderRadius sRight = .only(
    topRight: Radius.circular(8.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius sVertical = .vertical(
    top: Radius.circular(8.0),
    bottom: Radius.circular(8.0),
  );
  static const BorderRadius sHorizontal = .horizontal(
    left: Radius.circular(8.0),
    right: Radius.circular(8.0),
  );
  static const BorderRadius sTopLeft = .only(topLeft: Radius.circular(8.0));
  static const BorderRadius sTopRight = .only(topRight: Radius.circular(8.0));
  static const BorderRadius sBottomLeft = .only(
    bottomLeft: Radius.circular(8.0),
  );
  static const BorderRadius sBottomRight = .only(
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius sTopLeftBottomRight = .only(
    topLeft: Radius.circular(8.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius sTopRightBottomLeft = .only(
    topRight: Radius.circular(8.0),
    bottomLeft: Radius.circular(8.0),
  );
  static const BorderRadius sTopMLeft = .only(
    topLeft: Radius.circular(8.0),
    topRight: Radius.circular(16.0),
  );
  static const BorderRadius sRightMBottom = .only(
    topRight: Radius.circular(8.0),
    bottomLeft: Radius.circular(16.0),
  );
  static const BorderRadius sTopMRight = .only(
    topLeft: Radius.circular(8.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius sBottomMBottom = .only(
    bottomLeft: Radius.circular(8.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius sTopLLeft = .only(
    topLeft: Radius.circular(8.0),
    topRight: Radius.circular(24.0),
  );
  static const BorderRadius sRightLBottom = .only(
    topRight: Radius.circular(8.0),
    bottomLeft: Radius.circular(24.0),
  );
  static const BorderRadius sTopLRight = .only(
    topLeft: Radius.circular(8.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius sBottomLBottom = .only(
    bottomLeft: Radius.circular(8.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius m = .all(Radius.circular(16.0));
  static const BorderRadius mTop = .only(
    topLeft: Radius.circular(16.0),
    topRight: Radius.circular(16.0),
  );
  static const BorderRadius mBottom = .only(
    bottomLeft: Radius.circular(16.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius mLeft = .only(
    topLeft: Radius.circular(16.0),
    bottomLeft: Radius.circular(16.0),
  );
  static const BorderRadius mRight = .only(
    topRight: Radius.circular(16.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius mVertical = .vertical(
    top: Radius.circular(16.0),
    bottom: Radius.circular(16.0),
  );
  static const BorderRadius mHorizontal = .horizontal(
    left: Radius.circular(16.0),
    right: Radius.circular(16.0),
  );
  static const BorderRadius mTopLeft = .only(topLeft: Radius.circular(16.0));
  static const BorderRadius mTopRight = .only(topRight: Radius.circular(16.0));
  static const BorderRadius mBottomLeft = .only(
    bottomLeft: Radius.circular(16.0),
  );
  static const BorderRadius mBottomRight = .only(
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius mTopLeftBottomRight = .only(
    topLeft: Radius.circular(16.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius mTopRightBottomLeft = .only(
    topRight: Radius.circular(16.0),
    bottomLeft: Radius.circular(16.0),
  );
  static const BorderRadius mTopSLeft = .only(
    topLeft: Radius.circular(16.0),
    topRight: Radius.circular(8.0),
  );
  static const BorderRadius mRightSBottom = .only(
    topRight: Radius.circular(16.0),
    bottomLeft: Radius.circular(8.0),
  );
  static const BorderRadius mTopSRight = .only(
    topLeft: Radius.circular(16.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius mBottomSBottom = .only(
    bottomLeft: Radius.circular(16.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius mTopLLeft = .only(
    topLeft: Radius.circular(16.0),
    topRight: Radius.circular(24.0),
  );
  static const BorderRadius mRightLBottom = .only(
    topRight: Radius.circular(16.0),
    bottomLeft: Radius.circular(24.0),
  );
  static const BorderRadius mTopLRight = .only(
    topLeft: Radius.circular(16.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius mBottomLBottom = .only(
    bottomLeft: Radius.circular(16.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius l = .all(Radius.circular(24.0));
  static const BorderRadius lTop = .only(
    topLeft: Radius.circular(24.0),
    topRight: Radius.circular(24.0),
  );
  static const BorderRadius lBottom = .only(
    bottomLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius lLeft = .only(
    topLeft: Radius.circular(24.0),
    bottomLeft: Radius.circular(24.0),
  );
  static const BorderRadius lRight = .only(
    topRight: Radius.circular(24.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius lVertical = .vertical(
    top: Radius.circular(24.0),
    bottom: Radius.circular(24.0),
  );
  static const BorderRadius lHorizontal = .horizontal(
    left: Radius.circular(24.0),
    right: Radius.circular(24.0),
  );
  static const BorderRadius lTopLeft = .only(topLeft: Radius.circular(24.0));
  static const BorderRadius lTopRight = .only(topRight: Radius.circular(24.0));
  static const BorderRadius lBottomLeft = .only(
    bottomLeft: Radius.circular(24.0),
  );
  static const BorderRadius lBottomRight = .only(
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius lTopLeftBottomRight = .only(
    topLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(24.0),
  );
  static const BorderRadius lTopRightBottomLeft = .only(
    topRight: Radius.circular(24.0),
    bottomLeft: Radius.circular(24.0),
  );
  static const BorderRadius lTopSLeft = .only(
    topLeft: Radius.circular(24.0),
    topRight: Radius.circular(8.0),
  );
  static const BorderRadius lRightSBottom = .only(
    topRight: Radius.circular(24.0),
    bottomLeft: Radius.circular(8.0),
  );
  static const BorderRadius lTopSRight = .only(
    topLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius lBottomSBottom = .only(
    bottomLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(8.0),
  );
  static const BorderRadius lTopMLeft = .only(
    topLeft: Radius.circular(24.0),
    topRight: Radius.circular(16.0),
  );
  static const BorderRadius lRightMBottom = .only(
    topRight: Radius.circular(24.0),
    bottomLeft: Radius.circular(16.0),
  );
  static const BorderRadius lTopMRight = .only(
    topLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(16.0),
  );
  static const BorderRadius lBottomMBottom = .only(
    bottomLeft: Radius.circular(24.0),
    bottomRight: Radius.circular(16.0),
  );
}
