// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'spaces.dart';

// **************************************************************************
// SpacesGenerator
// **************************************************************************

// --------------------------------------------------
// This file was generated by the `dimengen` package.
// Any changes to this file may be lost during rebuild.
//
// Generator: https://pub.dev/packages/dimengen
// Author: http://github.com/warioddly
// --------------------------------------------------

abstract class Spaces {
  const Spaces._();

  static const SizedBox m = .square(dimension: 24.0);
  static const SizedBox mVertical = SizedBox(height: 24.0);
  static const SizedBox mHorizontal = SizedBox(width: 24.0);
  static SizedBox h(double value) => SizedBox(height: value);
  static SizedBox w(double value) => SizedBox(width: value);
  static SizedBox square(double value) => .square(dimension: value);
}
